---@type table<string, fun(cutscene:WorldCutscene)>
local depths = {}

function depths.start(cutscene)
    Game.world.music:stop()
    local kris = cutscene:getCharacter("kris")
    local susie = cutscene:getCharacter("susie")
    cutscene:fadeOut(0, {global = true})
    cutscene:detachCamera()
    cutscene:detachFollowers()
    kris:setSprite("fell")
    susie:setSprite("fell")
    kris:setPosition(Game.world.map:getMarker("spawn"))
    susie:setPosition(Game.world.map:getMarker("susiespawn"))
    cutscene:wait(1)
    cutscene:fadeIn(0, {global = true})
    Assets.playSound("noise")
    cutscene:wait(1)
    cutscene:text(Game:locRaw("depths_line19_1"), "bangs_neutral", susie)
    Assets.playSound("wing", 0.5)
    susie:shake()
    susie:setSprite("down")
    cutscene:text(Game:locRaw("depths_line23_1"), "sad", susie)
    cutscene:wait(2)
    Assets.playSound("wing", 0.5)
    kris:shake()
    kris:setSprite("sit")
    cutscene:wait(1)
    cutscene:text(Game:locRaw("depths_line29_1"), "neutral_side", susie)
    cutscene:text(Game:locRaw("depths_line30_1"), "nervous_side", susie)
    cutscene:wait(1)
    susie:setAnimation({"down_happy", 0.4, next="walk"})
    kris:setAnimation({"landed", 0.4, next="walk"})
    cutscene:wait(2)
    kris:setFacing("up")
    susie:setFacing("down")
    cutscene:text(Game:locRaw("depths_line37_1"))
    cutscene:wait(0.1)
    Assets.playSound("item")
    cutscene:text(Game:locRaw("depths_line40_1"))
    cutscene:text(Game:locRaw("depths_line41_1"))
    Game.world.music:play("endless_expanse")

    kris:setFacing("down")
    cutscene:interpolateFollowers()
    cutscene:attachCamera()
    cutscene:wait(cutscene:attachFollowers())
    Game:getQuest("mainline"):unlock()
end

return depths