---@type table<string, fun(cutscene:WorldCutscene)>
local depths = {}

function depths.start(cutscene)
    Game.world.music:stop()
    local kris = cutscene:getCharacter("kris")
    local susie = cutscene:getCharacter("susie")
    cutscene:fadeOut(0, {global = true})
    cutscene:detachCamera()
    cutscene:detachFollowers()
    kris:setSprite("fell")
    susie:setSprite("fell")
    kris:setPosition(Game.world.map:getMarker("spawn"))
    susie:setPosition(Game.world.map:getMarker("susiespawn"))
    cutscene:wait(1)
    cutscene:fadeIn(0, {global = true})
    Assets.playSound("noise")
    cutscene:wait(1)
    cutscene:text("* Ughhh...[wait:5] the hell happened...?", "bangs_neutral", susie)
    Assets.playSound("wing", 0.5)
    susie:shake()
    susie:setSprite("down")
    cutscene:text("* Kris...?[wait:5] Get up,[wait:5] Kris!", "sad", susie)
    cutscene:wait(2)
    Assets.playSound("wing", 0.5)
    kris:shake()
    kris:setSprite("sit")
    cutscene:wait(1)
    cutscene:text("* Damn,[wait:5] looks like we made it to...[wait:5] some kind of dark world...?", "neutral_side", susie)
    cutscene:text("* Let's get going,[wait:5] Kris,[wait:5] maybe Ralsei's here or something...", "nervous_side", susie)
    cutscene:wait(1)
    susie:setAnimation({"down_happy", 0.4, next="walk"})
    kris:setAnimation({"landed", 0.4, next="walk"})
    cutscene:wait(2)
    kris:setFacing("up")
    susie:setFacing("down")
    cutscene:text("* Before you went on with your adventure,[wait:5] you found something deep in your pockets...")
    cutscene:wait(0.1)
    Assets.playSound("item")
    cutscene:text("* You got the [color:yellow]ControlKey[color:reset]!")
    cutscene:text("* The [color:yellow]ControlKey[color:reset] was added to your Key Items.")
    Game.world.music:play("endless_expanse")

    kris:setFacing("down")
    cutscene:interpolateFollowers()
    cutscene:attachCamera()
    cutscene:wait(cutscene:attachFollowers())
    Game:getQuest("mainline"):unlock()
end

return depths