return {

    device = function(cutscene)
		if Plot:isBefore("shelter_heard_log") then
			local kris = assert(cutscene:getCharacter("kris"))
			local susie = cutscene:getCharacter("susie") or kris
			local noelle = cutscene:getCharacter("noelle") or susie
			Kristal.Console:log("device_used")   
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("devicecutscene_1"), "nervous")
			cutscene:text(Game:locRaw("devicecutscene_2"), "nervous") 
			cutscene:wait(cutscene:fadeOut())
			Game.world.music:play("omnis")
			cutscene:wait(1)
			cutscene:setSpeaker()
			cutscene:text(Game:locRaw("devicecutscene_3"))
			cutscene:text(Game:locRaw("devicecutscene_4"))
			cutscene:text(Game:locRaw("devicecutscene_5"))
			cutscene:text(Game:locRaw("devicecutscene_6"))
			cutscene:text(Game:locRaw("devicecutscene_7"))
			cutscene:text(Game:locRaw("devicecutscene_8"))
			cutscene:text(Game:locRaw("devicecutscene_9")) 
			cutscene:text(Game:locRaw("devicecutscene_10"))
			cutscene:text(Game:locRaw("devicecutscene_11"))
			cutscene:text(Game:locRaw("devicecutscene_12"))
			cutscene:text(Game:locRaw("devicecutscene_13"))
			cutscene:text(Game:locRaw("devicecutscene_14"))
			cutscene:text(Game:locRaw("devicecutscene_15"))
			cutscene:text(Game:locRaw("devicecutscene_16"))
			cutscene:text(Game:locRaw("devicecutscene_17"))
			cutscene:text(Game:locRaw("devicecutscene_18"))
			cutscene:text(Game:locRaw("devicecutscene_19"))
			cutscene:text(Game:locRaw("devicecutscene_20"))
			cutscene:text(Game:locRaw("devicecutscene_21"))
			cutscene:text(Game:locRaw("devicecutscene_22"))
			cutscene:text(Game:locRaw("devicecutscene_23"))
			cutscene:text(Game:locRaw("devicecutscene_24"))
			cutscene:text(Game:locRaw("devicecutscene_25"))
			cutscene:text(Game:locRaw("devicecutscene_26"))
			cutscene:text(Game:locRaw("devicecutscene_27"))
			cutscene:text(Game:locRaw("devicecutscene_28"))
			cutscene:wait(cutscene:fadeIn())
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("devicecutscene_29"), "sad")
			cutscene:text(Game:locRaw("devicecutscene_30"), "sad")
			cutscene:setSpeaker()
			Assets.playSound("phone")
			cutscene:wait(0.5)
			cutscene:text(Game:locRaw("devicecutscene_31"))
			Assets.playSound("item")
			cutscene:wait(0.3)
			cutscene:text(Game:locRaw("devicecutscene_32"))
			cutscene:setSpeaker(noelle)
			cutscene:text(Game:locRaw("devicecutscene_33"), "surprise_frown")
			cutscene:setSpeaker()
			cutscene:text(Game:locRaw("devicecutscene_34"))
			cutscene:setSpeaker(noelle)
			cutscene:text(Game:locRaw("devicecutscene_35"), "shock")
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("devicecutscene_36"), "surprise_frown")
			cutscene:setSpeaker()
			cutscene:text(Game:locRaw("devicecutscene_37"))
			cutscene:text(Game:locRaw("devicecutscene_38"))
			cutscene:text(Game:locRaw("devicecutscene_39"))
			cutscene:text(Game:locRaw("devicecutscene_40"))
			cutscene:text(Game:locRaw("devicecutscene_41"))
			cutscene:text(Game:locRaw("devicecutscene_42"))
			cutscene:text(Game:locRaw("devicecutscene_43"))
			Game.world.music:fade(0, 1)
			cutscene:wait(1)
			Game.world.music:play("in-the-shelter")
			Game.world.music:fade(1, 1)
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("devicecutscene_44"), "sad")
			cutscene:setSpeaker(noelle)
			cutscene:text(Game:locRaw("devicecutscene_45"), "sad_smile_b")
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("devicecutscene_46"), "neutral_side")
			cutscene:text(Game:locRaw("devicecutscene_47"), "neutral")
			cutscene:text(Game:locRaw("devicecutscene_48"), "surprise_smile")
			SetPlot("shelter_heard_log")
			Game:getQuest("shelter"):complete()
			Game:getQuest("gateway"):unlock()
		else 
			cutscene:setSpeaker("susie")
			cutscene:text(Game:locRaw("devicecutscene_49"), "nervous_side")
		end;
    end,

    }