return {

    device = function(cutscene)
		if Plot:isBefore("shelter_heard_log") then
			local kris = assert(cutscene:getCharacter("kris"))
			local susie = cutscene:getCharacter("susie") or kris
			local noelle = cutscene:getCharacter("noelle") or susie
			Kristal.Console:log("device_used")   
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("device_device_1"), "nervous")
			cutscene:text(Game:locRaw("device_device_2"), "nervous") 
			cutscene:wait(cutscene:fadeOut())
			Game.world.music:play("omnis")
			cutscene:wait(1)
			cutscene:setSpeaker()
			cutscene:text(Game:locRaw("device_device_3"))
			cutscene:text(Game:locRaw("device_device_4"))
			cutscene:text(Game:locRaw("device_device_5"))
			cutscene:text(Game:locRaw("device_device_6"))
			cutscene:text(Game:locRaw("device_device_7"))
			cutscene:text(Game:locRaw("device_device_8"))
			cutscene:text(Game:locRaw("device_device_9")) 
			cutscene:text(Game:locRaw("device_device_10"))
			cutscene:text(Game:locRaw("device_device_11"))
			cutscene:text(Game:locRaw("device_device_12"))
			cutscene:text(Game:locRaw("device_device_13"))
			cutscene:text(Game:locRaw("device_device_14"))
			cutscene:text(Game:locRaw("device_device_15"))
			cutscene:text(Game:locRaw("device_device_16"))
			cutscene:text(Game:locRaw("device_device_17"))
			cutscene:text(Game:locRaw("device_device_18"))
			cutscene:text(Game:locRaw("device_device_19"))
			cutscene:text(Game:locRaw("device_device_20"))
			cutscene:text(Game:locRaw("device_device_21"))
			cutscene:text(Game:locRaw("device_device_22"))
			cutscene:text(Game:locRaw("device_device_23"))
			cutscene:text(Game:locRaw("device_device_24"))
			cutscene:text(Game:locRaw("device_device_25"))
			cutscene:text(Game:locRaw("device_device_26"))
			cutscene:text(Game:locRaw("device_device_27"))
			cutscene:text(Game:locRaw("device_device_28"))
			cutscene:wait(cutscene:fadeIn())
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("device_device_29"), "sad")
			cutscene:text(Game:locRaw("device_device_30"), "sad")
			cutscene:setSpeaker()
			Assets.playSound("phone")
			cutscene:wait(0.5)
			cutscene:text(Game:locRaw("device_device_31"))
			Assets.playSound("item")
			cutscene:wait(0.3)
			cutscene:text(Game:locRaw("device_device_32"))
			cutscene:setSpeaker(noelle)
			cutscene:text(Game:locRaw("device_device_33"), "surprise_frown")
			cutscene:setSpeaker()
			cutscene:text(Game:locRaw("device_device_34"))
			cutscene:setSpeaker(noelle)
			cutscene:text(Game:locRaw("device_device_35"), "shock")
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("device_device_36"), "surprise_frown")
			cutscene:setSpeaker()
			cutscene:text(Game:locRaw("device_device_37"))
			cutscene:text(Game:locRaw("device_device_38"))
			cutscene:text(Game:locRaw("device_device_39"))
			cutscene:text(Game:locRaw("device_device_40"))
			cutscene:text(Game:locRaw("device_device_41"))
			cutscene:text(Game:locRaw("device_device_42"))
			cutscene:text(Game:locRaw("device_device_43"))
			Game.world.music:fade(0, 1)
			cutscene:wait(1)
			Game.world.music:play("in-the-shelter")
			Game.world.music:fade(1, 1)
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("device_device_44"), "sad")
			cutscene:setSpeaker(noelle)
			cutscene:text(Game:locRaw("device_device_45"), "sad_smile_b")
			cutscene:setSpeaker(susie)
			cutscene:text(Game:locRaw("device_device_46"), "neutral_side")
			cutscene:text(Game:locRaw("device_device_47"), "neutral")
			cutscene:text(Game:locRaw("device_device_48"), "surprise_smile")
			SetPlot("shelter_heard_log")
			Game:getQuest("shelter"):complete()
			Game:getQuest("gateway"):unlock()
		else 
			cutscene:setSpeaker("susie")
			cutscene:text(Game:locRaw("device_device_49"), "nervous_side")
		end;
    end,

    }