return {

    UNUSED = function(cutscene)
        cutscene:text(Game:locRaw("housetext_dess_1")) 
    end,
    dessroom = function(cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text(Game:locRaw("housetext_dessroom_1"), "smile_side") 
        cutscene:setSpeaker(susie)
        cutscene:text(Game:locRaw("housetext_dessroom_2"), "sus_nervous")
    end,
    basement = function(cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text(Game:locRaw("housetext_basement_1"), "surprise_smile_b") 
        cutscene:text(Game:locRaw("housetext_basement_2"), "smile_closed") 
        cutscene:setSpeaker(susie)
        cutscene:text(Game:locRaw("housetext_basement_3"), "sincere_smile") 
        cutscene:setSpeaker(noelle)
        cutscene:text(Game:locRaw("housetext_basement_4"), "smile")
        Assets.playSound("dooropen")
        Game.world:mapTransition("noelles house/basement/basement")
    end,
    noelleroom = function(cutscene, event)
        cutscene:text(Game:locRaw("housetext_noelleroom_1"))
        if cutscene:choicer({ Game:locRaw("housetext_noelleroom_choice_1"), Game:locRaw("housetext_noelleroom_choice_2") }) == 1 then
            local kris = assert(cutscene:getCharacter("kris"))
            local noelle = cutscene:getCharacter("noelle")
            local susie = cutscene:getCharacter("susie")
            Assets.playSound("dooropen")
            cutscene:fadeOut(0.5, { music = true })
            cutscene:wait(2)
            cutscene:detachFollowers()
            cutscene:wait(cutscene:mapTransition("noelles house/noelle room"))
            cutscene:wait(0.5)
            local kris = assert(cutscene:getCharacter("kris"))
            local noelle = cutscene:getCharacter("noelle")
            local susie = cutscene:getCharacter("susie")
            cutscene:detachFollowers()
            cutscene:fadeIn(1)
            kris:setFacing("left")
            susie:setFacing("left")
            noelle:setFacing("left")
            cutscene:wait(0.7)
            cutscene:walkTo(kris, "kris1")
            cutscene:walkTo(susie, "susie1")
            cutscene:walkTo(noelle, "noelle1")
            cutscene:setSpeaker(susie)
            cutscene:text(Game:locRaw("housetext_noelleroom_2"), "stupid")
            cutscene:setSpeaker(noelle)
            cutscene:text(Game:locRaw("housetext_noelleroom_3"), "blush_finger")
            Game.world.music:fade(1, 1)
            cutscene:wait(0.5)
            Assets.playSound("wing")
            cutscene:shakeCharacter(susie)
            cutscene:shakeCharacter(noelle)
            susie:setPosition(Game.world.map:getMarker("susie2"))
            noelle:setPosition(Game.world.map:getMarker("noelle2"))
            susie:setSprite("sit")
            noelle:setSprite("sitdown_bed")
            Game.world.music:play("noellehouse")
            Game.world.music:fade(1, 1)
            cutscene:setSpeaker(noelle)
            cutscene:text(Game:locRaw("housetext_noelleroom_4"), "blush_smile_closed")
            cutscene:setSpeaker(susie)
            cutscene:text(Game:locRaw("housetext_noelleroom_5"), "stupid")
            cutscene:setSpeaker(noelle)
            cutscene:text(Game:locRaw("housetext_noelleroom_6"), "blush_surprise_smile")
            cutscene:setSpeaker(susie)
            cutscene:text(Game:locRaw("housetext_noelleroom_7"), "shock_nervous")
            cutscene:text(Game:locRaw("housetext_noelleroom_8"), "sad")
            cutscene:setSpeaker(noelle)
            cutscene:text(Game:locRaw("housetext_noelleroom_9"), "blush_smile")
            cutscene:setSpeaker(susie)
            cutscene:text(Game:locRaw("housetext_noelleroom_10"), "shy_down")
            cutscene:text(Game:locRaw("housetext_noelleroom_11"), "shy")
            cutscene:text(Game:locRaw("housetext_noelleroom_12"), "sincere")
            cutscene:setSpeaker(noelle)
            cutscene:text(Game:locRaw("housetext_noelleroom_13"), "dejected")
            cutscene:setSpeaker(susie)
            cutscene:text(Game:locRaw("housetext_noelleroom_14"), "sus_nervous")
            cutscene:text(Game:locRaw("housetext_noelleroom_15"), "sad")
            cutscene:text(Game:locRaw("housetext_noelleroom_16"), "smile")
            cutscene:setSpeaker(noelle)
            cutscene:text(Game:locRaw("housetext_noelleroom_17"), "confused")
            cutscene:setSpeaker(susie)
            cutscene:text(Game:locRaw("housetext_noelleroom_18"), "sus_nervous")
            cutscene:text(Game:locRaw("housetext_noelleroom_19"), "smirk")
            cutscene:setSpeaker(noelle)
            cutscene:text(Game:locRaw("housetext_noelleroom_20"), "question")
            cutscene:text(Game:locRaw("housetext_noelleroom_21"), "question")
            cutscene:setSpeaker(susie)
            cutscene:text(Game:locRaw("housetext_noelleroom_22"), "closed_grin")
            cutscene:text(Game:locRaw("housetext_noelleroom_23"), "nervous_side")
            cutscene:setSpeaker(noelle)
            cutscene:text(Game:locRaw("housetext_noelleroom_24"), "blush_smile")
            cutscene:setSpeaker(susie)
            cutscene:text(Game:locRaw("housetext_noelleroom_25"), "sincere_smile")
            cutscene:setSpeaker(noelle)
            cutscene:text(Game:locRaw("housetext_noelleroom_26"), "blush_big_smile")
            Assets.playSound("wing")
            Game.world.music:fade(0, 1)
            cutscene:shakeCharacter(susie)
            cutscene:shakeCharacter(noelle)
            kris:resetSprite()
            noelle:resetSprite()
            susie:resetSprite()
            kris:setFacing("right")
            susie:setFacing("right")
            noelle:setFacing("right")
            susie:setPosition(Game.world.map:getMarker("susie1"))
            noelle:setPosition(Game.world.map:getMarker("noelle1"))
            cutscene:walkTo(kris, "outsideofmap", 10)
            cutscene:walkTo(susie, "outsideofmap", 10)
            cutscene:walkTo(noelle, "outsideofmap", 10)
            cutscene:fadeOut(1.5, { music = true })
            cutscene:wait(1.5)
            cutscene:attachFollowers()
            cutscene:mapTransition("hometown/town_north", 480, 344)
            Game.world.music:play("hometown")
            cutscene:wait(cutscene:fadeIn(1, { music = true }))
            Game:getQuest("getnoelle"):complete()
            Game:getQuest("supplies"):unlock()
        else
            cutscene:text(Game:locRaw("housetext_noelleroom_27"))
        end
    end,
    parentroom = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(susie)
        cutscene:text(Game:locRaw("housetext_parentroom_1"), "stupid") 
        cutscene:text(Game:locRaw("housetext_parentroom_2"), "nervous_side") 
        cutscene:setSpeaker(noelle)
        cutscene:text(Game:locRaw("housetext_parentroom_3"), "sad_smile") 
        cutscene:setSpeaker(susie)
        cutscene:text(Game:locRaw("housetext_parentroom_4"), "sincere_smile") 
        cutscene:setSpeaker(noelle)
        cutscene:text(Game:locRaw("housetext_parentroom_5"), "smile_closed_b") 
        cutscene:text(Game:locRaw("housetext_parentroom_6"), "smile_closed_b") 
    end,
    bathroom = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(susie)
        cutscene:text(Game:locRaw("housetext_bathroom_1"), "stupid") 
        cutscene:text(Game:locRaw("housetext_bathroom_2"), "nervous") 
        cutscene:setSpeaker(noelle)
        cutscene:text(Game:locRaw("housetext_bathroom_3"), "blush_surprise_smile") 
        cutscene:setSpeaker(susie)
        cutscene:text(Game:locRaw("housetext_bathroom_4"), "teeth") 
    end,
    workroom = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text(Game:locRaw("housetext_workroom_1"), "frown") 
        cutscene:text(Game:locRaw("housetext_workroom_2"), "smile_closed") 
    end,
    fridge = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:text(Game:locRaw("housetext_fridge_1")) 
        cutscene:setSpeaker(noelle)
        cutscene:text(Game:locRaw("housetext_fridge_2"), "sad_smile_b") 
        cutscene:setSpeaker(susie)
        cutscene:text(Game:locRaw("housetext_fridge_3"), "shy_down") 
        cutscene:text(Game:locRaw("housetext_fridge_4"), "susie_dream_grin")
    end,
    sitdown = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:text(Game:locRaw("housetext_fridge_5")) 
        cutscene:setSpeaker(noelle)
        cutscene:text(Game:locRaw("housetext_fridge_6"), "sad_smile_b") 
        cutscene:setSpeaker(susie)
        cutscene:text(Game:locRaw("housetext_fridge_7"), "shy_down") 
        cutscene:text(Game:locRaw("housetext_fridge_8"), "susie_dream_grin")
    end,
}