---@type table<string, fun(cutscene:WorldCutscene, ...):...>
local spireCutsenes = {

    moneyfount = function(cutscene, event)
        cutscene:text("* (It's a familiar pool...)[wait:5]\n* (A waterfall is almost flowing endlessly out of it.)")
        cutscene:text("* (You feel the need to donate.)[wait:5]\n* (Throw some money in?)")
        cutscene:showShop()
        local choice = cutscene:choicer({ "Yes", "No" })
        if choice == 1 then
            if Game.money > 0 then
                Game.money = Game.money - 1
                Assets.playSound("item")
                cutscene:text("* (You threw a dollar in the pool. A feeling of calm washes over you.)")
                cutscene:hideShop()
            else
                cutscene:hideShop()
                cutscene:text("* (You don't have any money.)")
            end
        else
            cutscene:hideShop()
            cutscene:text("* (The pool glimmers in the dusk.)")
        end
    end;

    phone = function(cutscene, event)
        cutscene:text("* You pick up the new phone.")
        Assets.playSound("phone1")
        cutscene:wait(5)
        cutscene:text("* It's not connected. ")
    end;

    flowers = function(cutscene, event)
        cutscene:text("* (It's a vase of wilting flowers.)")
        cutscene:text("* (Regardless of their condition,[wait:5] they feel right at home.)")
    end;

    TV = function(cutscene, event)
        cutscene:text("* It's Torenna the Television![wait:10]\n* Your brand new TV!")
        cutscene:text("* Despite the lack of power elsewhere in town,[wait:5] the TV is on.")
        cutscene:text("* It's stuck on an image of a snowy landscape.")
    end;

    picture = function(cutscene, event)
        cutscene:text("* (A picture frame has fallen off the dresser onto the floor.)")
        cutscene:text("* (What an unfortunate sight.)")
    end;

    curtain = function(cutscene, event)
        cutscene:text("* (The curtains from the shower have been removed.)")
        cutscene:text("* (This bathroom has seen better days.)")
    end;

    cracks = function(cutscene, event)
        cutscene:text("* (Your fathers shop has suffered some minor cosmetic damages.)")
        cutscene:text("* (It'd be surprising if anyone else were to notice.)")
    end;

    susieMeeting = function(cutscene, event)
        if Plot:isBefore("night_met_susie") then
            Game.world.music:fade(0, 1)
            local susie = assert(cutscene:getCharacter("susie_lw"), "tf you mean there's no susie??? how??")
            susie:setSprite("chill")
            local kris = cutscene:getCharacter("kris")
            local x, y = cutscene:getMarker("kris1")
            cutscene:walkTo(kris, x, y, 6, "down")
            cutscene:wait(4)
            Game.world.music:play("house")
            local x, y = cutscene:getMarker("susie1")
            cutscene:shakeCharacter(susie)
            susie:setSprite("angry_down")
            cutscene:slideTo(susie, x, y, 0.1)
            cutscene:wait(0.1)
            cutscene:shakeCharacter(susie)


            cutscene:setSpeaker(susie)
            Assets.playSound("scare")
            cutscene:wait(4)
            cutscene:look(kris, "left")
            cutscene:wait(1)
            cutscene:look(kris, "up")
            cutscene:wait(2)
            susie:setSprite("unhappy_left")
            cutscene:look(susie, "left")
            cutscene:text("* [wait:10].[wait:10].[wait:10].", "nervous_side")
            Assets.playSound("bump")
            susie:setSprite("away_scratch")
            susie.sprite:play(0.3, loop)
            cutscene:wait(1)
            cutscene:text("* Uh...[wait:10] about time you showed up..", "nervous_side")
            local x, y = cutscene:getMarker("susie2")
            susie:resetSprite()
            cutscene:walkTo(susie, x, y, 2, "down")
            cutscene:wait(1)
            cutscene:look(kris, "left")
            cutscene:wait(1.3)
            cutscene:look(susie, "right")
            cutscene:wait(0.3)
            cutscene:text("* I noticed the abandoned shelter door is open south of town..", "nervous_side")
            cutscene:look(susie, "down")
            cutscene:text("* ...which,[wait:5] uh,[wait:5] doesn't seem right.", "nervous_side")
            cutscene:text("* The police haven't caught onto it...[wait:10] must have opened recently.", "smirk")
            cutscene:text("* Problem is,[wait:5] it doesn't look like there's a Dark World in there...[wait:5]", "smirk")
            cutscene:text("* ...so we should probably gather some,[wait:5] uh,[wait:5] stuff.[wait:10] To defend ourselves.",
                "nervous")
            cutscene:shakeCharacter("kris")
            Assets.playSound("bump")
            cutscene:wait(0.5)
            cutscene:look(susie, "right")
            cutscene:wait(2)
            cutscene:text("* Look,[wait:5] Kris,[wait:5] I know that place shakes you up a bit,[wait:5] but...", "annoyed_down")
            cutscene:text("* If we could scare the Knight off last night...", "annoyed")
            cutscene:text("* ...we can scare whatever's in that creepy old bunker.", "teeth_smile")
            cutscene:text("* Y'know,[wait:5] I suspect it may have something to do with the-", "closed_grin", { auto = true })
            local rumble = Assets.playSound("rumble")
            rumble:setLooping(true)
            susie:setSprite("shocked")
            cutscene:shakeCamera()
            susie:alert()
            kris:alert()
            Game.world.timer:every(0.3, function()
                cutscene:shakeCamera()
            end, 12)
            cutscene:wait(3)
            susie:resetSprite()
            Assets.stopSound("rumble")
            cutscene:wait(0.3)
            cutscene:wait(0.3)
            cutscene:text("* ...earthquakes.", "suspicious")
            cutscene:text(
            "* Damn,[wait:5] another one?[wait:10] That's like,[wait:5] uh,[wait:5] 3,[wait:5] in the last hour...", "smirk")
            cutscene:wait(2)
            cutscene:text("* Let's go back to my apartment and gather some stuff.", "neutral")
            cutscene:text("* Oh wait,[wait:5] uhhh,[wait:5] we should probably go get Noelle.", "neutral")
            cutscene:text("* I wouldn't want her to miss out on another adventure.", "smile")


            Game:addPartyMember("susie")
            susie = susie:convertToFollower()
            SetPlot("night_met_susie")
            cutscene:attachFollowers()
            Game.world.music:play("hometown")
            Game.world.music:fade(1, 1)
            Game:getQuest("meetsusie"):complete()
            Game:getQuest("getnoelle"):unlock()
        else
            local susie = assert(cutscene:getCharacter("susie_lw"), "tf you mean there's no susie??? how??")
            susie:resetSprite()
        end; 
    end;


    damnitkris = function(cutscene, event)
        local susie = cutscene:getCharacter("susie")
        cutscene:wait(2)
        cutscene:setSpeaker("susie")
        susie:setSprite("turn_around")
        Assets.playSound("whip_hard")
        cutscene:wait(1.5)
        cutscene:text("GOD FUCKING DAMNIT KRIS,[wait:5] WHERE THE HELL ARE WE?", "teeth")
        susie:resetSprite()
    end;

    dumpstablook = function(cutscene, event)
        if event.interact_count == 1 then
            Assets.playSound("slurp")
            cutscene:text("* ") -- add slurp noise here
            cutscene:wait(0.03)
            cutscene:text("* (They're drinking from a cup labeled \"Ghost Juice.\")")
            cutscene:text("* (It's best not to bother them.)")
        else
            Assets.playSound("slurp")
            cutscene:wait(1)
        end
    end;

    happstablook = function(cutscene, event)
        if event.interact_count == 1 then
            cutscene:text("* Hello darling...")
            cutscene:text("* I'm oh so tired..[wait:10] but it'd be wrong of me to sleep when the rest are out here.")
            cutscene:text("* These outages are really doing a number on the town...")
            cutscene:text(
            "* I've barely had time to catch up on my favorite show![wait:10] Isn't this just a mess,[wait:5] darling?")
        elseif event.interact_count == 2 then
            cutscene:text("* You're quite talkative this evening,[wait:5] aren't you.")
        elseif event.interact_count > 2 then
            cutscene:text("* Off with you now,[wait:5] darling.")
        end
    end;


    madstablook = function(cutscene, event)
        if event.interact_count == 1 then
            cutscene:text("* These power outages are TOO MUCH!!![wait:10] TOO MUCH I TELL YOU!!!!!")
            cutscene:text("* I just got the PERFECT GAMING SETUP!![wait:10] The computer with rainbow lights and all!!")
            cutscene:text("* ...but it isn't enough... [wait:10]It's just NEVER ENOUGH IS IT!!")
            cutscene:text("* At least I have one thing on those STUPID.[wait:10] STUPID.[wait:10] STUPID CONSOLE GAMERS!!")
            cutscene:text("* They'll never beat my style.[wait:10] My flare.[wait:10] My pure WILL TO GAME!!")
        elseif event.interact_count == 2 then
            cutscene:text("* I!!![wait:10] CAN'T!!![wait:10] STAND!!![wait:10] THIS!!! ")
            cutscene:text("* It's just so...[wait:10] MISERABLE OUT HERE!! ")
        elseif event.interact_count >= 3 then
            cutscene:text("* Stop reminding me. ")
        end
    end;


    catti = function(cutscene, event)
        cutscene:setSpeaker("alphys")
        cutscene:text("*[voice:reset] ...you have to partner with Berdly?", "catti_up")
        cutscene:text("*[voice:reset] Sorry for your loss...", "catti_down")
    end;

    mkid = function(cutscene, event)
        cutscene:text("*[voice:reset] Yo,[wait:5] Kris![wait:5] You gotta partner with Berdly!?")
        cutscene:text("*[voice:reset] Well,[wait:5] at least you'll get an A...[wait:5] maybe.")
    end;

    tem = function(cutscene, event)
        if event.interact_count == 1 then
            cutscene:text("*[voice:reset] KRISP!![wait:5]\n* tem lost eg,[wait:5] but tem have new partner!")
        elseif event.interact_count >= 2 then
            cutscene:text("*[voice:reset] tem partner with...[wait:5]\nEG SISTER!!")
        end
    end;

    snowy = function(cutscene, event)
        cutscene:text("*[voice:reset] Hey,[wait:5] Kris! Why shouldn't you take up time travel?")
        cutscene:text("*[voice:reset] Because there's NO FUTURE in it!![wait:5] Ha ha ha![wait:5] What'd you think!?[wait:5] Funny,[wait:5] right!?")
        cutscene:text("*[voice:reset] ...")
        cutscene:text("*[voice:reset] Kris,[wait:5] you've gotta be less silent if you want anybody other than Noelle to talk to you.")
    end;
    
    jockington = function(cutscene, event)
        cutscene:text("*[voice:reset] Kris![wait:5] You KNOW Jockington and Catti are ALWAYS partners!")
        cutscene:text("*[voice:reset] Didn't Ms. Alphys tell you to partner with Berdly?")
    end;

    blocked = function(cutscene, event)
        local kris = assert(cutscene:getCharacter("kris"))
        cutscene:setSpeaker("susie")
        cutscene:text("* (Kris,[wait:5] we're going to Castle Town,[wait:5] RIGHT??)", "shy")
        cutscene:wait(cutscene:walkTo(kris, kris.x, kris.y+30))
    end;

    blockedalph = function(cutscene, event)
        local kris = assert(cutscene:getCharacter("kris"))
        cutscene:setSpeaker("alphys")
        cutscene:text("* L-lets go towards the unused classroom!", "nervous_angry")
        cutscene:wait(cutscene:walkTo(kris, kris.x, kris.y+30))
    end;

    school = function(cutscene, event)
        Game:setFlag("susieGone", true)
        local interactionsAlph = Plot:get() - 5000
        if interactionsAlph == 0 then
            Music:stop()
            local kris = cutscene:getCharacter("kris")
            local susie = cutscene:getCharacter("susie_lw") or cutscene:spawnNPC("susie_lw", 0, 0)
            kris.visible = false
            susie.visible = false
            local berdly = cutscene:getCharacter("berdly") or cutscene:spawnNPC("berdly_lw", 0, 0)


            local x, y = cutscene:getMarker("kris1")
            cutscene:walkTo(kris, x, y, 1, "down")
            cutscene:look(berdly, "up")

            local alphys = cutscene:getCharacter("alphys_lw")
            cutscene:setSpeaker(alphys)
            cutscene:wait(1)
            cutscene:text("* So,[wait:5] does everyone have a...", "smile")
            local img1 = Game.world.map:getImageLayer("dooropen")
            Assets.playSound("dooropen")
            img1.visible = true
            kris.visible = true
            cutscene:look(alphys, "right")

            cutscene:wait(1)
            local x, y = cutscene:getMarker("kris2")
            cutscene:walkTo(kris, x, y, 0.5, "down")
            cutscene:wait(0.5)
            Assets.playSound("doorclose")
            img1.visible = false
            cutscene:wait(1)
            cutscene:text("* Oh...[wait:10] K-Kris...\n[wait:10] * We thought you weren't coming today!", "shock")
            cutscene:text("* We're doing group projects this month...", "smile")
            cutscene:text("* A-and,[wait:5] uh...[wait:10]", "nervous_angry")
            cutscene:wait(0.5)
            cutscene:look(alphys, "down")
            cutscene:wait(1.5)
            cutscene:look(alphys, "right")
            cutscene:text("* I don't think... [wait:10]anyone else is free of a partner this time,[wait:5] so...",
                "nervous_concern")
            cutscene:text("* Oh![wait:10] You can partner with Berdly!", "blush")
            cutscene:text("* Noelle called in sick today,[wait:5] so I guess that works out for you...", "nervous_b")
            cutscene:wait(1)
            cutscene:look(alphys, "down")
            cutscene:wait(1)
            cutscene:look(alphys, "right")
            cutscene:text("* G-go sit down![wait:10] You can sit in Noelle's seat for today.", "nervous_angry")
            local x, y = cutscene:getMarker("kris3")
            cutscene:walkTo(kris, x, y, 0.5, "down")
            cutscene:wait(0.5)
            local x, y = cutscene:getMarker("kris4")
            cutscene:walkTo(kris, x, y, 3, "left")
            cutscene:wait(3)
            cutscene:look(berdly, "left")
            cutscene:look(alphys, "down")
            local x, y = cutscene:getMarker("kris5")
            cutscene:walkTo(kris, x, y, 0.5, "down")
            cutscene:wait(0.5)
            local x, y = cutscene:getMarker("kris6")
            cutscene:walkTo(kris, x, y, 1, "right")
            cutscene:wait(1)
            Game.world.music:play("school")
            cutscene:look(kris, "down")
            Plot:set("nf_school_interact1Alph")
        elseif interactionsAlph == 1 then
            local kris = assert(cutscene:getCharacter("kris"))
            local alphys = cutscene:getCharacter("alphys_lw")
            cutscene:look(alphys, "right")
            cutscene:setSpeaker(alphys)
            cutscene:text("* K-Kris,[wait:5] I know partnering with Berdly isn't the BEST,[wait:5] but...", "nervous", "alphys")
            cutscene:text("* I don't think your mother would be happy if you left the class...", "nervous_b", "alphys")
            cutscene:wait(cutscene:walkTo(kris, kris.x, kris.y+20))
        elseif interactionsAlph == 2 then
            local alphys = cutscene:getCharacter("alphys_lw")
            cutscene:setSpeaker("alphys_lw")
            cutscene:look(alphys, "right")
            cutscene:wait(1)
            cutscene:text("* H-hey Kris...", "smile")
            cutscene:text("* Before you leave-", "nervous_angry")
            cutscene:text("* If you see Susie in the halls...", "nervous_concern")
            cutscene:wait(1)
            cutscene:text("* Tell her I said thank you.", "nervous")
            Plot:set("nf_school_interact3Alph")
            event:remove()
        elseif interactionsAlph == 4 then
            --not needed due to what the next one does
        elseif interactionsAlph == 5 then
            event:remove()
            --WHERE THE SUSIE FLAG SHOULD GO GRAHHHHHHHH
            Music:stop()
            local kris = cutscene:getCharacter("kris")
            local susie = cutscene:getCharacter("susie_lw")
            local berdly = cutscene:getCharacter("berdly_lw") or cutscene:spawnNPC("berdly_lw",0,0)
            cutscene:detachFollowers()
            cutscene:look(berdly, "up")
            kris.visible = false
            susie.visible = false
            local alphys = cutscene:getCharacter("alphys_lw")
            cutscene:setSpeaker("alphys_lw")
            cutscene:look(alphys, "down")
            local x, y = cutscene:getMarker("kris1")
            cutscene:walkTo(kris, x, y, 1, "down")
            local x, y = cutscene:getMarker("kris1")
            cutscene:walkTo(susie, x, y, 1, "down")
            cutscene:wait(1)
            cutscene:text("* From here on out,[wait:5] let's try to be a little nicer to her,[wait:5] okay?", "smile")
            cutscene:text("*[voice:reset] ...", "catti_down")
            cutscene:text("*[voice:reset] ...I'll try.", "catti_up")
            --Kris and Susie walk in
            local img1 = Game.world.map:getImageLayer("dooropen")
            Assets.playSound("dooropen")
            img1.visible = true
            kris.visible = true
            cutscene:wait(1)
            local x, y = cutscene:getMarker("kris2")
            cutscene:walkTo(kris, x, y, 1, "down")
            cutscene:wait(1)
            local x, y = cutscene:getMarker("krisstand")
            cutscene:walkTo(kris, x, y, 1, "left")
            cutscene:wait(1)
            susie.visible = true
            local x, y = cutscene:getMarker("susie1")
            cutscene:walkTo(susie, x, y, 1.5, "down")
            cutscene:wait(0.7)
            Assets.playSound("doorclose")
            img1.visible = false



            cutscene:look(alphys, "right")
            cutscene:text("*[voice:alphys] O-oh hello Kris,[wait:5] hello Susie!", "shock")
            cutscene:look(susie, "left")
            cutscene:text("* Great timing,[wait:5] we were just about to talk about the rubric.", "smile")
            cutscene:text("* Go take a seat so we can get started!", "smile")
            cutscene:wait(1)
            cutscene:setSpeaker("susie")
            cutscene:text("* Uhhhh...[wait:10]\n * About that.", "sus_nervous")
            cutscene:text("* I left my...[wait:10] Calculator.[wait:10] In the supply closet.", "sus_nervous")
            cutscene:text("* And it's locked.[wait:10] I really need to get it because,[wait:5] uh...", "nervous_side")
            cutscene:look(susie, "down")
            cutscene:text("* ...y'know,[wait:5] I really don't want to fail that upcoming test.", "nervous")
            cutscene:setSpeaker("alphys_lw")
            cutscene:wait(1)
            cutscene:look(alphys, "left")
            cutscene:wait(0.5)
            cutscene:look(alphys, "right")
            cutscene:text("* W-we don't have a test anytime soon,[wait:5] Susie...", "shock_smile")
            cutscene:text("* But studying early is a good thing!!", "blush")
            cutscene:look(susie, "left")
            cutscene:text("* Your test grades last time weren't...[wait:10] the b-best...", "nervous")
            cutscene:setSpeaker("susie")
            cutscene:wait(1)
            cutscene:text("* ...", "sus_nervous")
            cutscene:look(susie, "down")
            cutscene:text("* ...Yeah I'll uh,[wait:10] I'll do better next time.", "nervous")
            cutscene:look(alphys, "right")
            cutscene:setSpeaker("alphys_lw")
            cutscene:wait(1)
            cutscene:look(susie, "left")
            cutscene:text("* You said the closet is locked...?", "concern")
            cutscene:text("* T-thats odd,[wait:5] We always leave it open during school hours.", "nervous_concern")
            cutscene:text("* I lost the key to it a few days ago,[wait:5] but...", "neutral")
            cutscene:text("* If you really need it,[wait:5] you could try the unused classroom?", "nervous")
            cutscene:text("* There's a door in there,[wait:5] though i-if the main door's locked...", "nervous_concern")
            cutscene:setSpeaker("susie")
            cutscene:wait(1)
            cutscene:text("* ...The unused classroom's door is locked,[wait:5] too.", "teeth_smile")
            --alphys looks around in panic
            cutscene:setSpeaker("alphys")
            cutscene:wait(1)
            cutscene:look(alphys, "left")
            cutscene:wait(0.2)
            cutscene:look(alphys, "up")
            cutscene:wait(0.2)
            cutscene:look(alphys, "down")
            cutscene:wait(0.2)
            cutscene:look(alphys, "right")
            cutscene:text("* WHY???", "shock_smile")
            cutscene:text("* O-OKAY...[wait:5] Um...", "nervous_angry")
            cutscene:text("* I don't know why a-all the doors are locked,[wait:5] but...", "nervous_b")
            local x, y = cutscene:getMarker("alphys1")
            cutscene:walkTo(alphys, x, y, 3, "right")
            cutscene:text("* I'll go unlock it for you...", "nervous_concern")
            cutscene:look(alphys, "down")
            Assets.playSound("wing")
            cutscene:wait(1)
            cutscene:setSpeaker("susie")
            cutscene:text("* Oh,[wait:5] uh,[wait:5] Kris also needs to come with,[wait:5] because...", "nervous")
            cutscene:look(alphys, "right")
            cutscene:text("* ...", "nervous_side")
            cutscene:setSpeaker("alphys")
            cutscene:text("* T-that's okay,[wait:5] they can come with us,[wait:5] Susie...", "nervous")
            cutscene:text("* But you guys are going to need to s-stay with me!", "nervous_angry")
            local x, y = cutscene:getMarker("alphys2")
            cutscene:walkTo(alphys, x, y, 2, "right")
            cutscene:wait(2)
            cutscene:text("* Class,[wait:5] stay put!! A-and if I don't come back soon...", "nervous_angry")
            cutscene:look(alphys, "down")
            cutscene:text("* Call Toriel.", "nervous_b")
            Game:addPartyMember("alphys")
            alphys = alphys:convertToFollower()
            cutscene:attachFollowers()
            Game.world.music:play("school")
            cutscene:look(kris, "down")
            --Alphys joins party
            Plot:set("nf_school_interact6Alph")
        end
    end;


    berdly = function(cutscene, event)
        if Plot:isBefore("nf_school_interact2Alph") then
            local alphys = cutscene:getCharacter("alphys_lw")
            local berdly = cutscene:getCharacter("berdly_lw")
            local susie = cutscene:getCharacter("susie_lw")
            local kris = cutscene:getCharacter("kris")
            cutscene:setSpeaker("berdly")
            cutscene:text("* Bold of you to assume I'd partner with you,[wait:5] KRIS!", "neutral")
            cutscene:text("* I get it,[wait:5] don't worry.", "neutral")
            cutscene:text("* Who WOULDN'T want to partner with me!", "LMAO")
            cutscene:text("* After all,[wait:5] I am the smartest student in class...", "smirk")
            local x, y = cutscene:getMarker("alphys1")
            cutscene:walkTo(alphys, x, y, 2, "right")
            cutscene:text("* But I'm reserved for the second smartest.[wait:10]\n* Sorry Kris.  ", "smirk")
            cutscene:text("* Maybe Susan will show up for once,[wait:5] you two would make a great pair!", "LMAO")
            cutscene:look(alphys, "up")
            cutscene:wait(1)
            cutscene:look(berdly, "up")
            cutscene:wait(1)
            cutscene:look(berdly, "left")
            cutscene:wait(0.5)
            cutscene:text("* ...", "neutral")
            cutscene:text("* I guess your last project grade wasn't THAT[wait:5] bad...", "surprised")
            cutscene:text("* ...Do you,[wait:5] actually want to partner with me,[wait:5] or..", "worried_smile", "berdly")
            local choice = cutscene:choicer({ "Yes", "No" })
            if choice == 1 then
                cutscene:text("* Really!?[wait:5] Well,[wait:5] great!", "surprised")
                cutscene:text("* For once in your life you made a GOOD choice![wait:5] Good job,[wait:5] Kris!", "LMAO")
                cutscene:look(alphys, "down")
                cutscene:text("* Now you can FINALLY get an \"A+\" instead of-", "smirk", { auto = true })
            else
                cutscene:text("* HEY![wait:10] I-I didn't want to partner with you anyways!", "angry")
                cutscene:look(alphys, "down")
                cutscene:text("* I don't need my \"A+\" streak ruined by a \"C+\" stu-", "angry", { auto = true })
            end
            cutscene:setSpeaker("alphys")
            cutscene:look(berdly, "up")
            cutscene:look(kris, "up")
            cutscene:text("* Uh...[wait:10]\n * H-has anyone seen the chalk?", "concern_lw")
            cutscene:text("* This is the third time it's gone missing,[wait:5] and...", "nervous")
            cutscene:text("* Y-you all know I can't start class without-", "nervous_concern", { auto = true })
            Music:stop()
            local img1 = Game.world.map:getImageLayer("dooropen")
            Assets.playSound("dooropen")
            img1.visible = true
            susie.visible = true
            local x, y = cutscene:getMarker("susie1")
            cutscene:wait(1)
            cutscene:look(alphys, "right")
            cutscene:text("* H...\n * Hi,[wait:5] SUSIE.", "shock_smile")
            cutscene:walkTo(susie, x, y, 1, "down")
            cutscene:setSpeaker("susie")
            cutscene:wait(1.5)
            cutscene:text("* Hey...[wait:10]\n * Sorry I'm late,[wait:5] again.", "nervous_side")
            cutscene:text("* Had a,[wait:5] uh,[wait:5] stomach bug.[wait:10]\n* Or something...", "nervous")
            cutscene:wait(1)
            cutscene:look(susie, "left")
            cutscene:text("* Also,[wait:5] here's the chalk that's been missing.", "smirk")
            local x, y = cutscene:getMarker("susie2")
            cutscene:walkTo(susie, x, y, 2, "left")
            cutscene:wait(2.5)
            Assets.playSound("bump")
            cutscene:wait(1)
            cutscene:text("* Found it in the supply closet.", "teeth_smile")
            cutscene:wait(0.5)
            cutscene:setSpeaker("alphys")
            cutscene:wait(1)
            cutscene:look(alphys, "left")
            cutscene:wait(0.3)
            cutscene:look(alphys, "up")
            cutscene:wait(0.3)
            cutscene:look(alphys, "down")
            cutscene:wait(0.3)
            cutscene:look(alphys, "right")
            cutscene:wait(1)
            cutscene:text("* T-thank you,[wait:5] Susie.", "nervous_b")
            cutscene:text("* We can finally start our l-lesson plan for the week...", "nervous_blush")
            cutscene:text("* We are,[wait:5] way,[wait:5] behind schedule.", "nervous_concern")
            cutscene:wait(1)
            cutscene:text("* Are you u-uhhh...[wait:10]\n * Is everything alright,[wait:5] Susie?", "nervous")
            cutscene:text("* You're acting rather strange today...", "nervous_b")
            cutscene:wait(1)
            cutscene:wait(0.5)
            cutscene:setSpeaker("susie")
            cutscene:look(susie, "right")
            cutscene:wait(0.5)
            cutscene:look(susie, "left")
            cutscene:text("* Yeah I uh,[wait:5] gotta leave.", "sus_nervous")
            cutscene:text("* Sorry about that,[wait:5] I guess.", "neutral")
            cutscene:setSpeaker("alphys")
            local x, y = cutscene:getMarker("susie1")
            cutscene:walkTo(susie, x, y, 3, "right")
            cutscene:wait(1)
            cutscene:text("* W-wait don't leave![wait:10]\n * We really need to get back on schedule!", "nervous_concern")
            cutscene:look(susie, "left")
            cutscene:text("* If you need help at home don't be afraid to tell me!", "nervous_concern")
            cutscene:wait(1)
            cutscene:look(susie, "right")
            cutscene:setSpeaker("susie")
            cutscene:text("* Kris,[wait:5] your uh...[wait:10]\n * Mom is outside.[wait:10] Waiting for you.", "suspicious")
            cutscene:text("* And Alphys...", "nervous_side")
            cutscene:look(susie, "right")
            cutscene:wait(2)
            cutscene:look(susie, "left")
            cutscene:text("* I'll try to be back soon,[wait:5] alright?", "sincere")
            cutscene:wait(1)
            local x, y = cutscene:getMarker("susie3")
            cutscene:walkTo(susie, x, y, 2, "up")
            cutscene:wait(2)
            susie.visible = false
            Assets.playSound("doorclose")
            img1.visible = false
            cutscene:wait(2)
            cutscene:setSpeaker("alphys_lw")
            cutscene:text("* Bye,[wait:5] S-Susie.", "nervous_concern")
            cutscene:wait(2)
            cutscene:look(alphys, "down")
            cutscene:text("* Kris,[wait:5] you should probably go catch up with your mother.", "smile")
            cutscene:text("* (Shouldn't she be teaching her class right now...?)", "neutral_L")
            Game.world.music:play("school")
            cutscene:look(kris, "down")
            Plot:set("nf_school_interact2Alph")
        else
            cutscene:text("* Looks like our partnership must be put to a halt,[wait:5] Kris!", "LMAO", "berdly")
        end;
    end;


    outside = function(cutscene, event)
        local interactionsSus = Game:getFlag("interactedSus", 0)
        if interactionsSus == 0 then
            local susie = cutscene:getCharacter("susie_lw")

            local kris = cutscene:getCharacter("kris")

            cutscene:look(kris, "down")
            cutscene:look(susie, "left")
            cutscene:setSpeaker("susie")
            cutscene:wait(2)
            cutscene:look(kris, "right")
            cutscene:text("* Hey Kris,[wait:5] uhh...", "nervous_side")

            cutscene:wait(0.5)
            --Spins in a circle looking around
            cutscene:look(susie, "down")
            cutscene:wait(0.3)
            cutscene:look(susie, "up")
            cutscene:wait(0.3)
            cutscene:look(susie, "right")
            cutscene:wait(0.3)
            cutscene:look(susie, "left")
            cutscene:wait(0.3)
            --Runs to kris
            cutscene:wait(1)
            local x, y = cutscene:getMarker("susie1")
            cutscene:walkTo(susie, x, y, 0.3, "left")
            cutscene:wait(0.4)
            --Susie starts shaking kris
            cutscene:shakeCamera()
            Assets.playSound("wing")
            susie.visible = false
            kris:setSprite("shake")
            kris.sprite:play(0.08)

            cutscene:text("* KRIS,[wait:5] WHAT THE HELL JUST HAPPENED???", "teeth_b")
            cutscene:text("* Like,[wait:5] genuinely,[wait:5] what was ANY of that??", "teeth")
            cutscene:shakeCamera()
            --Stop shaking
            Assets.playSound("bump")
            susie.visible = true
            kris:resetSprite()
            cutscene:look(susie, "left")
            cutscene:wait(1)
            --Turn down
            cutscene:look(susie, "down")
            cutscene:wait(1)
            cutscene:text("* Everyone is acting so...[wait:10] Normal!!![wait:10] ABOUT EVERYTHING!!!", "shy_b")
            cutscene:text("* It's like they all just...[wait:10] FORGOT!!!", "shy_b")
            --Looks at kris
            --Starts shaking kris
            cutscene:shakeCamera()
            Assets.playSound("wing")
            susie.visible = false
            kris:setSprite("shake")
            kris.sprite:play(0.08)

            cutscene:text("* DO YOU REMEMBER ANY OF THAT???", "teeth_b")
            cutscene:shakeCamera()
            Assets.playSound("wing")
            cutscene:text("* ARE YOU THE KRIS I REMEMBER???", "teeth_b")
            --Cutscene choicer "Yes, No"
            cutscene:wait(1)
            kris:setSprite("shake")
            kris.sprite:play(1)
            cutscene:wait(1)
            kris:setSprite("shake")
            kris.sprite:play(2)
            cutscene:wait(1)
            kris:setSprite("shake")
            kris.sprite:play(3)
            susie.visible = true
            kris:resetSprite()
            cutscene:look(susie, "left")
            susie.visible = false
            cutscene:shakeCamera()
            Assets.playSound("wing")
            kris:setSprite("shake")
            kris.sprite:play(0.08)
            cutscene:text("* ANSWER ME!!!!!", "teeth")

            local choice = cutscene:choicer({ "Yes", "I don't remember you" })
            Assets.playSound("bump")
            susie.visible = true
            kris:resetSprite()
            cutscene:look(susie, "left")
            cutscene:wait(1)
            if choice == 2 then
                cutscene:text("* Dude,[wait:5] I can HEAR the sarcasm.[wait:10] Now's not the time for that.", "nervous")
                cutscene:wait(1)
            end
            cutscene:text("* Okay.[wait:10] Alright.[wait:10] I'm okay.[wait:10] You're okay.[wait:10] Right??", "nervous")
            cutscene:wait(1.5)
            susie:setSprite("exasperated")
            cutscene:shakeCamera()
            Assets.playSound("wing")
            cutscene:text("* YOU'RE OKAY RIGHT????", "teeth_b")
            --Cutscene choicer "Yes, No"
            local choice = cutscene:choicer({ "I'm alright", "No I'm not" })
            susie:resetSprite()
            if choice == 2 then
                cutscene:text("* Dude,[wait:5] STOP MESSING AROUND ALREADY!!!![wait:10] Phew...", "nervous")
                cutscene:wait(1)
            else
                cutscene:text("* Alright.[wait:10] Phew.", "nervous_side")
            end
            cutscene:text("* Sorry about...[wait:10] all of that.", "sus_nervous")
            cutscene:text("* I'm just,[wait:5] y'know,[wait:5] veeery confused...", "suspicious")
            cutscene:wait(1.5)
            cutscene:look(susie, "up")
            cutscene:wait(1.5)
            cutscene:look(susie, "down")
            cutscene:text("* Do you think Ralsei's alright?", "annoyed")
            cutscene:look(susie, "left")
            cutscene:text("* After that guy...", "annoyed_down")
            cutscene:text("* ...", "bangs_neutral")
            cutscene:wait(1)
            cutscene:text("* Uhh...", "annoyed_down")
            cutscene:text("* Let's go check Castle Town.", "annoyed")
            Game:addPartyMember("susie")
            susie = susie:convertToFollower()
            cutscene:attachFollowers()
            Game.world.music:play("school", 1, 0.95)
            cutscene:look(kris, "down")
            Plot:set("nf_school_interact4Alph")
        end
        Game:setFlag("interactedSus", interactionsSus + 1)
    end;

    closet = function(cutscene, event)
        local susie = cutscene:getCharacter("susie_lw")
        if not Plot:isBefore("nf_school_interact5Alph") then
            cutscene:text("* Let's go talk to Alphys.[wait:10]\n* Maybe she has a key.", "nervous_side", "susie")
            return
        end
        cutscene:setSpeaker("susie")
        cutscene:text("* It's...[wait:10] locked?", "surprise_frown")
        cutscene:text("* Why is it locked while school is in session?", "suspicious")
        cutscene:text("* Maybe the door inside the unused classroom is open...", "nervous_side")
    end;

    classroom1 = function(cutscene, event)
        if not Game:hasPartyMember("alphys") then
            if not Plot:isBefore("nf_school_interact5Alph") then
                cutscene:text("* Let's go talk to Alphys.[wait:10]\n* Maybe she has a key.", "nervous_side", "susie")
                return
            end
            local susie = cutscene:getCharacter("susie_lw")
            cutscene:setSpeaker("susie")
            cutscene:text("* This one's locked too??", "sad")
            cutscene:text("* I guess it has no use being unlocked anymore...?", "suspicious")
            cutscene:wait(1)
            cutscene:look(susie, "left")
            cutscene:wait(0.5)
            cutscene:look(susie, "right")
            cutscene:text("* Let's go talk to Alphys.[wait:10]\n* Maybe she has a key.", "nervous_side")
            Plot:set("nf_school_interact5Alph")
        else
            local susie = cutscene:getCharacter("susie_lw")
            local kris = cutscene:getCharacter("kris")
            local alphys = cutscene:getCharacter("alphys")
            cutscene:detachCamera()
            cutscene:detachFollowers()
            Game.world.camera.keep_in_bounds = false
            local x, y = cutscene:getMarker("focus")
            print(x)
            Game.world.camera:panTo("focus", 0.5)
            local x, y = cutscene:getMarker("kris1")
            cutscene:walkTo(kris, x, y, 0.5, "up")
            local x, y = cutscene:getMarker("susie1")
            cutscene:walkTo(susie, x, y, 0.5, "up")
            local x, y = cutscene:getMarker("alphys1")
            cutscene:walkTo(alphys, x, y, 3, "up")
            cutscene:setSpeaker("alphys")
            cutscene:wait(2.5)
            cutscene:text("* A-alright,[wait:5] let me go ahead and unlock this for you two.", "concern")
            Assets.playSound("wing")
            cutscene:wait(1)
            cutscene:text("* Sorry about that,[wait:5] I have no clue why all these doors are locked.", "nervous")
            cutscene:wait(2)
            Assets.playSound("bump")
            cutscene:wait(1)
            cutscene:look(alphys, "down")
            cutscene:text("* ...I-it isn't unlocking.", "nervous_b")
            cutscene:text("* I could try...", "neutral")
            cutscene:look(alphys, "up")
            cutscene:wait(0.5)
            Assets.playSound("bump")
            cutscene:shakeCharacter(alphys)
            cutscene:wait(2)

            cutscene:text("* That didn't work either-", "nervous_concern", { auto = true })
            local obj = Game.world.map:getEvent(42)
            Assets.playSound("locker")
            obj.visible = true

            local obj2 = Game.world.map:getTileLayer("tile2")
            obj2.visible = true
            local obj3 = Game.world.map:getTileLayer("tile3")
            obj3.visible = true
            local obj6 = Game.world.map:getTileLayer("wall2")
            obj6.visible = true
            Game.world.music:play("door 2", 1.5, 1.0)
            cutscene:shakeCamera()
            cutscene:wait(2)
            local x, y = cutscene:getMarker("susie2")
            cutscene:walkTo(susie, x, y, 1, "up", true)
            local x, y = cutscene:getMarker("alphys2")
            cutscene:walkTo(alphys, x, y, 1, "up", true)
            cutscene:wait(1)
            cutscene:text("* W-what??", "nervous_b")
            cutscene:look(susie, "left")
            cutscene:look(kris, "right")
            cutscene:text("* It's a bit d-darker than usual in there...[react:1]", "nervous_concern",
                { reactions = { { "Another \nDark World??", "right", "bottom", "nervous_side", "susie" }, } })
            cutscene:wait(1)
            cutscene:look(alphys, "down")
            cutscene:wait(0.5)
            cutscene:look(susie, "up")
            cutscene:look(kris, "up")
            cutscene:text("* Don't worry kids![wait:10] I-I'll turn on the lights!", "nervous_b")

            local x, y = cutscene:getMarker("alphys3")
            cutscene:walkTo(alphys, x, y, 2, "up")
            local x, y = cutscene:getMarker("focus")
            print(x)
            Game.world.camera:panTo("focus1", 2.5)
            cutscene:wait(1.3)
            local obj4 = Game.world.map:getTileLayer("shadow")
            obj4.visible = true
            local obj5 = Game.world.map:getTileLayer("wall")
            obj5.visible = false
            local darken_fx = obj6:addFX(RecolorFX(), "darken")
            Game.world.timer:tween(2, darken_fx, { color = { 0, 0, 0, 1 } })
            local darken_fx = obj:addFX(RecolorFX(), "darken")
            Game.world.timer:tween(2, darken_fx, { color = { 0, 0, 0, 1 } })
            local darken_fx = obj3:addFX(RecolorFX(), "darken")
            Game.world.timer:tween(2, darken_fx, { color = { 0, 0, 0, 1 } })
            local obj7 = Game.world.map:getTileLayer("plaster")
            obj7.visible = false
            cutscene:wait(2.5)

            cutscene:wait(1)
            cutscene:look(alphys, "left")
            cutscene:wait(0.3)
            cutscene:look(alphys, "up")
            cutscene:wait(0.3)
            cutscene:look(alphys, "down")
            cutscene:wait(0.3)
            cutscene:look(alphys, "right")
            cutscene:wait(1)
            cutscene:text("* Wow,[wait:5] I can't see ANYTHING...", "shock_smile")
            cutscene:look(alphys, "up")
            cutscene:text("* Typically the light switch is right around here,[wait:5] but...", "concern")
            local x, y = cutscene:getMarker("alphys4")
            cutscene:walkTo(alphys, x, y, 1, "up", true)
            cutscene:look(susie, "left")
            cutscene:look(kris, "right")
            cutscene:text("* I c-can't feel the walls...", "nervous_concern")
            cutscene:look(alphys, "down")
            cutscene:look(susie, "up")
            cutscene:look(kris, "up")
            cutscene:text("* You guys stay out there!![wait:10] I-I'll find the switch,[wait:5] I promise!", "nervous")
            cutscene:wait(1)
            local obj8 = Game.world.map:getTileLayer("tile2")
            local darken_fx = obj8:addFX(RecolorFX(), "darken")
            Game.world.timer:tween(2, darken_fx, { color = { 0, 0, 0, 1 } })
            local obj9 = Game.world.map:getEvent(21)
            local darken_fx = obj9:addFX(RecolorFX(), "darken")
            Game.world.timer:tween(2, darken_fx, { color = { 0, 0, 0, 1 } })
            local x, y = cutscene:getMarker("alphys5")
            cutscene:walkTo(alphys, x, y, 3, "left")
            Game.world.camera:panTo("focus2", 4)
            cutscene:wait(2)
            cutscene:setSpeaker("susie")
            local x, y = cutscene:getMarker("kris2")
            cutscene:walkTo(kris, x, y, 1, "up", true)
            cutscene:wait(1)
            cutscene:look(susie, "left")
            cutscene:look(kris, "right")
            cutscene:text("* We just sealed this fountain like a week ago!", "surprise_frown")
            cutscene:text("* Why is there another one,[wait:5] especially after all of that...?", "suspicious")
            cutscene:look(alphys, "right")
            cutscene:wait(0.3)
            cutscene:look(alphys, "up")
            cutscene:wait(0.3)
            cutscene:setSpeaker("alphys")
            cutscene:text("* N-nothing over here either,[wait:5] I-I don't know what's going on!", "nervous_b")
            cutscene:text("* (Maybe I can just get to the door from inside?)", "neutral_L")
            local x, y = cutscene:getMarker("alphys6")
            cutscene:walkTo(alphys, x, y, 3, "left")
            Game.world.camera:panTo("focus3", 4)
            cutscene:wait(3)
            cutscene:setSpeaker("susie")
            cutscene:look(susie, "up")
            cutscene:text("* Hey Alphys...[wait:10] I think you should get back here,[wait:5] it's okay.", "smirk")
            cutscene:look(kris, "up")
            cutscene:text("* I'll...[wait:10] uh,[wait:5] go find another calculator at home...", "nervous_side")
            cutscene:wait(1)
            cutscene:look(alphys, "left")
            cutscene:wait(0.3)
            cutscene:look(alphys, "up")
            cutscene:wait(0.3)
            cutscene:look(alphys, "down")
            cutscene:wait(0.3)
            cutscene:look(alphys, "right")
            cutscene:wait(1)
            cutscene:setSpeaker("alphys")
            cutscene:text("* Hey Kris,[wait:5] hey Susie?", "nervous")
            cutscene:look(alphys, "left")
            cutscene:wait(1)
            cutscene:look(alphys, "right")
            cutscene:wait(1)
            cutscene:look(alphys, "down")
            cutscene:text("* I-I can't see the exit anymore...", "nervous_concern")
            cutscene:wait(1)
            local x, y = cutscene:getMarker("alphys7")
            cutscene:walkTo(alphys, x, y, 7, "right")
            Game.world.camera:panTo("focus4", 8)
            cutscene:wait(4)
            cutscene:setSpeaker("susie")
            cutscene:text("* Hey![wait:10] HEY!!![wait:10] We're right here!!!", "teeth")
            cutscene:wait(2.5)
            cutscene:look(alphys, "left")
            cutscene:wait(1)
            cutscene:setSpeaker("alphys")
            cutscene:text("* G-guys??[wait:10] Where are you?[react:1]", "nervous_b",
                { reactions = { { "LITERALLY RIGHT\nHERE!!", "right", "bottom", "teeth_b", "susie" }, } })
            cutscene:setSpeaker("susie")
            cutscene:look(alphys, "left")
            cutscene:wait(1)
            cutscene:look(alphys, "down")
            cutscene:setSpeaker("alphys")
            cutscene:text("* This better not be some cruel prank!!", "nervous_angry")
            cutscene:wait(1)
            cutscene:look(alphys, "left")
            cutscene:wait(0.3)
            cutscene:look(alphys, "up")
            cutscene:wait(0.3)
            cutscene:look(alphys, "down")
            cutscene:wait(0.3)
            cutscene:look(alphys, "right")
            cutscene:text("* You better speak up before-", "nervous_angry", { auto = true })
            cutscene:shakeCamera()
            alphys:alert()
            alphys:setSprite("shock")
            local rumble = Assets.playSound("rumble")
            Music:stop()
            rumble:setLooping(true)
            cutscene:wait(1)
            alphys:resetSprite()
            local x, y = cutscene:getMarker("alphys8")
            cutscene:walkTo(alphys, x, y, 2, "down", true)
            cutscene:wait(3)
            Assets.playSound("locker")
            cutscene:shakeCamera()
            cutscene:wait(1)
            Assets.stopSound("rumble")
            alphys:setSprite("fall")
            alphys.sprite:play(0.05, loop)
            cutscene:shakeCamera()
            local x, y = cutscene:getMarker("alphys9")
            cutscene:slideTo(alphys, x, y, 1)
            cutscene:wait(2)
            Game.world.camera:panTo("focus1", 0.2)
            cutscene:wait(0.2)
            cutscene:setSpeaker("susie")
            obj4.visible = false
            cutscene:text("* After her,[wait:5] Kris!!!", "teeth_b")
            cutscene:shakeCamera()

            cutscene:gotoCutscene("createTransitionCutscene.outskirts", {
                characters = {kris, susie}
            })
            Game.world.camera.keep_in_bounds = true
            cutscene:attachCamera()
        end
    end;

    alphyswarn = function(cutscene, event)
        local kris = assert(cutscene:getCharacter("kris"))
        cutscene:setSpeaker("alphys")
        cutscene:text("* L-lets go towards the unused classroom!", "nervous_angry")
        cutscene:wait(cutscene:walkTo(kris, kris.x-20, kris.y))
    end;

    alphyswarnb = function(cutscene, event)
        local kris = assert(cutscene:getCharacter("kris"))
        cutscene:setSpeaker("alphys")
        cutscene:text("* K-Kris,[wait:5] I'm sure your mother can wait a bit longer!", "nervous_angry")
        cutscene:wait(cutscene:walkTo(kris, kris.x, kris.y-20))
    end;

    susiewarn = function(cutscene, event)
        local kris = assert(cutscene:getCharacter("kris"))
        if Plot:isBefore("nf_school_interact5Alph") then
            cutscene:setSpeaker("susie")
            cutscene:text("* (Kris,[wait:5] I wasn't being serious when I said your mom was outside!!!!)", "shy")
            cutscene:wait(cutscene:walkTo(kris, kris.x, kris.y-20))
        else
            cutscene:setSpeaker("susie")
            cutscene:text("* (Kris,[wait:5] we're going to talk to Alphys about the locked doors!!)", "shy_b")
            cutscene:wait(cutscene:walkTo(kris, kris.x, kris.y-20))
        end
    end;
    susiewarnb = function(cutscene, event)
        local kris = assert(cutscene:getCharacter("kris"))
        if Plot:isBefore("nf_school_interact5Alph") then
            cutscene:setSpeaker("susie")
            cutscene:text("* (Kris,[wait:5] we're going to Castle Town,[wait:5] RIGHT??)", "shy")
            cutscene:wait(cutscene:walkTo(kris, kris.x-20, kris.y))
        else
            cutscene:setSpeaker("susie")
            cutscene:text("* (Kris,[wait:5] we're going to talk to Alphys about the locked doors!!)", "shy_b")
            cutscene:wait(cutscene:walkTo(kris, kris.x-20, kris.y))
        end
    end;
    awakening = function(cutscene, event)
        if Plot:isBefore("nf_awakened") then
            local alphys = cutscene:getCharacter("alphys")
            local kris = cutscene:getCharacter("kris")
            local susie = cutscene:getCharacter("susie")
            cutscene:fadeOut(0)
            cutscene:detachFollowers()
            local x, y = cutscene:getMarker("alphys10")
            cutscene:slideTo(alphys, x, y, 2)

            local x, y = cutscene:getMarker("kris10")
            cutscene:slideTo(kris, x, y, 2)

            local x, y = cutscene:getMarker("susie10")
            cutscene:slideTo(susie, x, y, 2)

            Assets.playSound("fallen")
            Game.fader:fadeIn(0)
            susie:setSprite("down")
            alphys:setSprite("fallen")
            kris:setSprite("landed")
            cutscene:wait(1)
            cutscene:setSpeaker("alphys")
            cutscene:shakeCharacter("alphys")
            Assets.playSound("bump")
            cutscene:wait(1)
            cutscene:text("* Owww...[wait:10] My head...", "concern_dark")
            cutscene:wait(1)
            alphys:resetSprite()
            Assets.playSound("noise")
            cutscene:shakeCamera()
            cutscene:wait(1)
            cutscene:look(alphys, "left")
            cutscene:wait(0.3)
            cutscene:look(alphys, "up")
            cutscene:wait(0.3)
            cutscene:look(alphys, "down")
            cutscene:wait(0.3)
            cutscene:look(alphys, "right")
            cutscene:fadeOut(0)
            Assets.playSound("locker")
            cutscene:wait(1)
            local wait, box = cutscene:text("[instant]To be continued...[stopinstant][wait:7s]", {auto = true, wait = false})
            box.box.visible = false
            box.text.alpha = 0
            box.text:fadeTo(1,1)
            cutscene:wait(3)
            box.text:fadeTo(0,1)
            cutscene:wait(wait)
            cutscene:wait(2)
            Plot:set("nf_awakened")
            local path = "saves/" .. Mod.info.id .. "/chapter7.json"
            love.filesystem.write(path, "1")
            Kristal.loadMod(Mod.info.id)
        end
    end;

    test = function(cutscene, event)
        local kris = cutscene:getCharacter("kris")
        cutscene:text("* Im a test cutscene! Let's play some sounds")
        Assets.stopSound("house")
        Assets.playSound("phone")
        cutscene:wait(2)
        cutscene:text("* Wow. Those sure were some sounds. Do a spin, kris! ")
        cutscene:look(kris, "down")
        cutscene:wait(0.5)
        cutscene:look(kris, "left")
        cutscene:wait(0.5)
        cutscene:look(kris, "up")
        cutscene:wait(0.5)
        cutscene:look(kris, "right")
        cutscene:wait(0.5)
        cutscene:look(kris, "down")
    end;
    ---@param cutscene WorldCutscene
    gate = function(cutscene)
        if not Plot:isBefore("holidayhouse_enter") then
            cutscene:text("* No need to go back.")
            return
        end
        if Plot:isBefore("night_met_susie") then
            cutscene:text("* (It's an ornate gate.)\n* (It appears to be locked.)")
            return
        end
        if Game:getFlag("silly_mode") then
            return cutscene:gotoCutscene("nightCutscenes.gateSilly")
        end
        Plot:set("holidayhouse_enter")
        local kris = assert(cutscene:getCharacter("kris"))
        local susie = cutscene:getCharacter("susie")
        local noelle = cutscene:getCharacter("noelle")
        Game:addPartyMember("noelle")
        cutscene:setSpeaker(susie)
        cutscene:text("* Oh, damn,[wait:5] forgot about this gate.", "neutral")
        cutscene:text("* So, uh... How the hell are we gonna get past it?", "neutral")
        if cutscene:choicer({ "Climb over", "Brute force" }) == 1 then
            cutscene:text("* That's a pretty damn good idea.[wait:5] Uhhh...[wait:5] step on my head,[wait:5] Kris!", "smile")
            cutscene:detachFollowers()
            cutscene:detachCamera()
            kris:walkTo(susie.x - 20, susie.y, 0.5, "left")
            susie:walkTo(kris.x, kris.y, 0.5, "left")
            cutscene:wait(1)
            kris:walkTo(susie.x + 20, susie.y, 0.5)
            cutscene:wait(0.5)
            kris:slideTo(susie.x, susie.y - 80, 0.5)
            cutscene:wait(1)
            cutscene:text("* Alright![wait:5] Jump over and open it for me,[wait:5] okay!?", "sincere_smile")
        else
            cutscene:text("* Hell yeah![wait:5] That's the spirit!", "surprise_smile")
            cutscene:text("* Uh...[wait:5] that actually might not be the best idea.", "stupid")
            cutscene:text("* How about we...[wait:5] climb over it![wait:5] Yeah![wait:5] Step on my head,[wait:5] Kris!", "smile")
            cutscene:detachFollowers()
            cutscene:detachCamera()
            kris:walkTo(susie.x - 20, susie.y, 0.5, "left")
            susie:walkTo(kris.x, kris.y, 0.5, "left")
            cutscene:wait(1)
            kris:walkTo(susie.x + 20, susie.y, 0.5)
            cutscene:wait(0.5)
            kris:slideTo(susie.x, susie.y - 80, 0.5)
            cutscene:wait(1)
            cutscene:text("* Alright![wait:5] Jump over and open it for me,[wait:5] okay!?", "sincere_smile")
        end
        cutscene:setSpeaker()
        cutscene:wait(cutscene:fadeOut(1.5, { music = true }))
        cutscene:setSpeaker()
        cutscene:text("* You knocked on the door to Noelle's house.[wait:5] She saw you and let you inside.")
        cutscene:setSpeaker(noelle)
        cutscene:text("* H-Hi guys![wait:5] What're you over here for?", "happy", "noelle")
        cutscene:setSpeaker(susie)
        cutscene:text("* We're uh...[wait:5] here to talk to you about something important.")
        cutscene:setSpeaker(noelle)
        cutscene:text("* Okay![wait:5] Let's go to my room,[wait:5] we'll talk there!", "happy", "noelle")
        cutscene:mapTransition("noelles house/living room/livingroom", 300, 465)
        Game.world.music:play("noellehouse")
        cutscene:fadeIn(1.5, { music = true })
    end;

    susieApartment = function (cutscene)
        if not Plot:isBefore("apartment_exit") then
            cutscene:text("* No need to go back.")
            return
        elseif Plot:isBefore("holidayhouse_enter") then
            cutscene:setSpeaker("susie")
            cutscene:text("* We should go get Noelle first,[wait:5] okay Kris?", "sad")
            return
        end
        -- All placeholder. Eventually, there will be a whole scene that plays. Hopefully. Mason note: no thanks.
        Plot:set("apartment_exit")
        local kris = assert(cutscene:getCharacter("kris"))
        local susie = cutscene:getCharacter("susie") or kris
        local noelle = cutscene:getCharacter("noelle") or susie
        cutscene:setSpeaker(susie)
        cutscene:text("* Okay,[wait:5] let's start grabbing some supplies.", "neutral")
        cutscene:text("* We have to get to the shelter before-", "annoyed")
        local rumble = Assets.playSound("rumble")
        rumble:setLooping(true)
        susie:setSprite("shocked")
        cutscene:shakeCamera()
        susie:alert()
        kris:alert()
        noelle:alert()
        Game.world.timer:every(0.3, function()
            cutscene:shakeCamera()
        end, 12)
        cutscene:wait(3)
        susie:resetSprite()
        Assets.stopSound("rumble")
        cutscene:wait(0.3)
        cutscene:wait(0.3)
        cutscene:text("* ...before that becomes a problem.", "suspicious")
        cutscene:wait(cutscene:fadeOut())
        cutscene:wait(1)
        cutscene:setSpeaker(noelle)
        cutscene:text("* Susie!![wait:5] Why do you have my coat on your floor???")
        cutscene:setSpeaker(susie)
        cutscene:text("* Uh...![wait:5] Just start grabbing stuff![wait:5] We've gotta hurry to the shelter!")
        cutscene:setSpeaker(noelle)
        cutscene:text("* (O-okay,[wait:5] Susie...)")
        cutscene:wait(1)
        Assets.playSound("wing")
        cutscene:wait(1)
        Assets.playSound("wing")
        cutscene:wait(1)
        Assets.playSound("wing")
        cutscene:wait(1)
        Assets.playSound("wing")
        cutscene:wait(1)
        Assets.playSound("wing")
        cutscene:wait(0.5)
        Assets.playSound("wing")
        cutscene:wait(0.5)
        Assets.playSound("wing")
        cutscene:wait(2)
        cutscene:setSpeaker(susie)
        cutscene:text("* Alright![wait:5] I think we've got enough![wait:5] Out the door!!!!")
        cutscene:wait(cutscene:fadeIn())
        cutscene:text("* Okay Kris,[wait:5] lead the way.[wait:5] And uh...[wait:5] hurry.", "sad")
        Game:getQuest("supplies"):complete()
        Game:getQuest("shelter"):unlock()
    end;

    noShelterYet = function (cutscene)
        if not Plot:isBefore("apartment_exit") then return end
        local kris = assert(cutscene:getCharacter("kris"))
        local susie = cutscene:getCharacter("susie")
        local noelle = cutscene:getCharacter("noelle")
        cutscene:text("* You think about if it's time to go to the shelter yet...", "neutral_side")

        if Plot:isBefore("holidayhouse_enter") then
            cutscene:text("* But you couldn't find Noelle.", "nervous")
        else
            cutscene:text("* But you didn't have any supplies.", "nervous")
        end
        cutscene:text("* You decided to take care of that first.")
        cutscene:wait(cutscene:walkTo(kris, kris.x, kris.y-20))
    end;

    ---@param cutscene WorldCutscene
    gateSilly = function(cutscene)
        local kris = assert(cutscene:getCharacter("kris"), "where kris???")
        local susie = assert(cutscene:getCharacter("susie"), "where susie???")
        cutscene:setSpeaker(susie)
        susie:setSprite("turn_around")
        Assets.playSound("whip_crack_only")
        cutscene:text("* God FUCKING DAMN IT,[wait:5] KRIS.[wait:10][func:endfunny]I forgot about this gate.", "neutral", nil,
            {
                functions = {
                    endfunny = function()
                        susie:resetSprite()
                    end
                }
            })
        susie:resetSprite()
        cutscene:wait(2)
        cutscene:text("* You know what I'm thinking?", "smile")
        cutscene:choicer({ "Hell Yeah", "Hell Yeah" })
        cutscene:text("* Course you are.[wait:5] Let's do it.", "smile")
        cutscene:detachFollowers()
        cutscene:detachCamera()
        kris:walkTo(susie.x - 20, susie.y, 0.5, "left")
        susie:walkTo(kris.x, kris.y, 0.5, "left")
        cutscene:wait(1)
        kris:walkTo(susie.x + 20, susie.y, 0.5)
        cutscene:wait(0.5)
        kris:slideTo(susie.x, susie.y - 80, 0.5)
        cutscene:wait(1)
        cutscene:text("* Wait, I think I see someone!", "surprise_frown")
        local carol_improvement = Sprite("sillymode/carol_improvement/a")
        carol_improvement:play(1 / 4)
        carol_improvement:setOrigin(1, 1)
        carol_improvement:setPosition(100, 370)
        Game.world:spawnObject(carol_improvement)
        carol_improvement.physics.speed_x = 4
        carol_improvement:setScale(0.5)
        cutscene:wait(function()
            return carol_improvement.x > (kris.x + 100)
        end)
        Mod.ghast_tear_real = true
        Game:load()
    end;
}

return spireCutsenes