return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 10,
  nextobjectid = 163,
  properties = {
    ["light"] = true,
    ["music"] = ""
  },
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/backgrounds/noelle room.png",
      id = 2,
      name = "house",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -0.00416667,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collisions",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65.9063,
          y = 2,
          width = 370.138,
          height = 141.97,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66.2111,
          y = 158.017,
          width = 55.7758,
          height = 146.045,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "",
          shape = "rectangle",
          x = 133.998,
          y = 321.998,
          width = 217.998,
          height = 45.5684,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 355.996,
          y = 322.003,
          width = 71.9939,
          height = 45.4763,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 435.989,
          y = 143.926,
          width = 75.5694,
          height = 62.2096,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 436.033,
          y = 285.532,
          width = 75.5694,
          height = 92.0278,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0.101664,
          y = 1.40277,
          width = 65.933,
          height = 376.361,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88.2153,
          y = 56.8195,
          width = 85.7512,
          height = 115.361,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65.9529,
          y = 367.455,
          width = 362.037,
          height = 10.5905,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "polyline",
          x = 66.1304,
          y = 361.87,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 1.73913, y = 0 },
            { x = 1.86957, y = 4.08696 },
            { x = 5.78261, y = 4.04348 },
            { x = 5.82609, y = 6.04348 }
          },
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "polyline",
          x = 427.969,
          y = 368,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 2.03125, y = 0 },
            { x = 2, y = -1.9375 },
            { x = 5.96875, y = -2.03125 },
            { x = 6.03125, y = -6 },
            { x = 8, y = -5.96875 }
          },
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 323.875,
          y = 152.063,
          width = 24.0625,
          height = 33.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 311.969,
          y = 129.972,
          width = 45.9716,
          height = 21.6023,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 186.029,
          y = 140.794,
          width = 121.999,
          height = 117.164,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "noelle2",
          type = "",
          shape = "point",
          x = 268,
          y = 167.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "spawn",
          type = "",
          shape = "point",
          x = 480,
          y = 256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "susie2",
          type = "",
          shape = "point",
          x = 192,
          y = 192,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "kris1",
          type = "",
          shape = "point",
          x = 363.545,
          y = 192.182,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "noelle1",
          type = "",
          shape = "point",
          x = 320,
          y = 192,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "susie1",
          type = "",
          shape = "point",
          x = 319.485,
          y = 216.515,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "outsideofmap",
          type = "",
          shape = "point",
          x = 480,
          y = 256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 115,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 506.538,
          y = 206.013,
          width = 6.5,
          height = 79.9219,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "noelles house/hallway",
            ["marker"] = "room"
          }
        },
        {
          id = 124,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 311.917,
          y = 140.334,
          width = 45.9792,
          height = 45.5205,
          rotation = 0,
          visible = true,
          properties = {
            ["solid"] = false,
            ["text1"] = "* There's a couple of pill bottles on the bedside table."
          }
        },
        {
          id = 156,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 87.9195,
          y = 55.967,
          width = 87.9792,
          height = 117.884,
          rotation = 0,
          visible = true,
          properties = {
            ["solid"] = false,
            ["text1"] = "* It's just a simple wardrobe.[wait:5] All of the clothes are the same."
          }
        },
        {
          id = 157,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 169.76,
          y = 270.058,
          width = 106.479,
          height = 79.884,
          rotation = 0,
          visible = true,
          properties = {
            ["solid"] = false,
            ["text1"] = "* It's an old television.[wait:5] It's off."
          }
        },
        {
          id = 158,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 277.76,
          y = 317.808,
          width = 44.229,
          height = 79.884,
          rotation = 0,
          visible = true,
          properties = {
            ["border"] = "leaves",
            ["solid"] = false,
            ["text1"] = "* It's a game console.[wait:5] There's a game of Dragon Blazers inserted."
          }
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/backgrounds/noelle room above.png",
      id = 9,
      name = "aboveplayer",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    }
  }
}
