return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 22,
  height = 16,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 9,
  nextobjectid = 121,
  properties = {
    ["border"] = "leaves",
    ["light"] = true,
    ["music"] = "noellehouse"
  },
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/backgrounds/livingroom normal.png",
      id = 2,
      name = "house",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 12,
      offsety = 7,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 22,
      height = 16,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collisions",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = -150,
          width = 672,
          height = 172,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65.3333,
          y = 178,
          width = 46,
          height = 51.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 447.5,
          y = 329.5,
          width = 37.5,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 386.5,
          y = 355,
          width = 160,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 690.227,
          y = 204.568,
          width = 93.5,
          height = 92.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 46.7087,
          y = 33.948,
          width = 537,
          height = 172,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 67.042,
          y = 167.615,
          width = 46,
          height = 51.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 447.334,
          y = 325.073,
          width = 37.5,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 385.626,
          y = 352.281,
          width = 160,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9.93565,
          y = 381.766,
          width = 41.5,
          height = 101.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11.9587,
          y = 7.19801,
          width = 51.5,
          height = 248.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 439.334,
          y = 346.323,
          width = 37.5,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 455.334,
          y = 313.823,
          width = 29.625,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "polyline",
          x = 891.709,
          y = 293.448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -288, y = 0.75 },
            { x = -336.75, y = 48.75 },
            { x = -336, y = 152.25 }
          },
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 349.527,
          y = 443.539,
          width = 208.583,
          height = 203.708,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10.7505,
          y = 445.094,
          width = 243.25,
          height = 203.708,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 675.042,
          y = 32.5313,
          width = 216.333,
          height = 172,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120.209,
          y = 141.948,
          width = 160,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "spawn1",
          type = "",
          shape = "point",
          x = 38.5,
          y = 310.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "door",
          type = "",
          shape = "point",
          x = 630.75,
          y = 231.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "susie1",
          type = "",
          shape = "point",
          x = 535,
          y = 225,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "susie2",
          type = "",
          shape = "point",
          x = 207,
          y = 222.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "susie3",
          type = "",
          shape = "point",
          x = 386.667,
          y = 282.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "focus",
          type = "",
          shape = "point",
          x = 350.667,
          y = 260.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "susie4",
          type = "",
          shape = "point",
          x = 556.667,
          y = 209.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "door2",
          type = "",
          shape = "point",
          x = 631,
          y = 212.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "spawn",
          type = "",
          shape = "point",
          x = 669.75,
          y = 247.25,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "offscreen",
          type = "",
          shape = "point",
          x = -120.554,
          y = 307.59,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "basement",
          type = "",
          shape = "point",
          x = 630.811,
          y = 231.595,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 114,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = -29.375,
          y = 255.458,
          width = 41.5,
          height = 126.833,
          rotation = 0,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text1"] = "* (No need to go upstairs...)"
          }
        },
        {
          id = 115,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 584.205,
          y = 152.841,
          width = 90.5,
          height = 36.5,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "noelles house/basement/basement",
            ["marker"] = "spawn"
          }
        },
        {
          id = 116,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 254.114,
          y = 504.962,
          width = 95.5,
          height = 36.5,
          rotation = 0,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text1"] = "* No need to go back..."
          }
        },
        {
          id = 119,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 0.916667,
          y = 255.583,
          width = 14.5,
          height = 126.5,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "noelles house/kitchen",
            ["marker"] = "spawn"
          }
        },
        {
          id = 120,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 584,
          y = 77.8335,
          width = 91.3182,
          height = 126.833,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "houseText.basement",
            ["solid"] = true
          }
        }
      }
    }
  }
}
