return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 34,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 6,
  nextobjectid = 50,
  properties = {
    ["border"] = "shelterdark",
    ["light"] = true,
    ["music"] = "core_approach"
  },
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "../../../../assets/sprites/backgrounds/coreleadup.png",
      id = 2,
      name = "coreleadup",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collisions",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 250.5,
          y = 1096,
          width = 60,
          height = 139,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 446,
          y = 442.5,
          width = 112,
          height = 666,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 140,
          width = 510.5,
          height = 188,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 327,
          width = 96,
          height = 118,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 551.5,
          y = 330,
          width = 102.5,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 226,
          y = 446,
          width = 112,
          height = 664,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 231,
          y = 1226.5,
          width = 49.5,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 212,
          y = 1342,
          width = 96,
          height = 42,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 308,
          y = 1360,
          width = 176,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 472,
          y = 1102,
          width = 88,
          height = 258,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "spawn",
          type = "",
          shape = "point",
          x = 341.751,
          y = 1297.14,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "exitingforreal",
          type = "",
          shape = "point",
          x = 393,
          y = 384.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 4,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280.667,
          y = 1235.33,
          width = 30.3333,
          height = 105.667,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "shelter/hallway",
            ["marker"] = "gatewayexit"
          }
        },
        {
          id = 45,
          name = "gatewayentry",
          type = "",
          shape = "rectangle",
          x = 316,
          y = 172,
          width = 150,
          height = 158,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 314.333,
          y = 313.167,
          width = 151.333,
          height = 27.667,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "gateway/core",
            ["marker"] = "spawn"
          }
        },
        {
          id = 49,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 337.818,
          y = 445.909,
          width = 108.242,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "shelter.gatewayEnter",
            ["once"] = false
          }
        }
      }
    }
  }
}
