return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 25,
  height = 16,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 9,
  nextobjectid = 133,
  properties = {
    ["light"] = true,
    ["music"] = "noellehouse"
  },
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/backgrounds/noellekitchen normal.png",
      id = 2,
      name = "house",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -0.00416667,
      offsety = -0.00555556,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 25,
      height = 16,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collisions",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = -150,
          width = 672,
          height = 172,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 545.333,
          y = 207.333,
          width = 46,
          height = 162.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 46.7087,
          y = 33.948,
          width = 537,
          height = 172,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 167.542,
          y = 182.115,
          width = 81,
          height = 51.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 277.626,
          y = 310.281,
          width = 268.667,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11.9587,
          y = 7.19801,
          width = 51.5,
          height = 248.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 501.334,
          y = 205.656,
          width = 43.8333,
          height = 105,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = -79.9162,
          y = 203.761,
          width = 243.25,
          height = 317.041,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 279.542,
          y = 137.281,
          width = 222.667,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "polyline",
          x = 797.333,
          y = 283.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -78, y = 0.666667 },
            { x = -76.6667, y = -222 }
          },
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "polyline",
          x = 238,
          y = 518.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 1.33333, y = -79.3333 },
            { x = 403.333, y = -80 },
            { x = 482.667, y = -158 },
            { x = 561.333, y = -158 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "spawn1",
          type = "",
          shape = "point",
          x = 38.5,
          y = 310.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "upstairs",
          type = "",
          shape = "point",
          x = 663,
          y = 221.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "susie1",
          type = "",
          shape = "point",
          x = 535,
          y = 225,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "susie4",
          type = "",
          shape = "point",
          x = 556.667,
          y = 209.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "spawn",
          type = "",
          shape = "point",
          x = 759.75,
          y = 329.25,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "workroom",
          type = "",
          shape = "point",
          x = 197.917,
          y = 460.083,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 115,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 619.538,
          y = 148.174,
          width = 90.5,
          height = 36.5,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "noelles house/hallway",
            ["marker"] = "spawn"
          }
        },
        {
          id = 123,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 785.583,
          y = 281.75,
          width = 14.5,
          height = 80.5,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "noelles house/living room/livingroom",
            ["marker"] = "spawn1"
          }
        },
        {
          id = 124,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 312.167,
          y = 97.3335,
          width = 46.1667,
          height = 126.833,
          rotation = 0,
          visible = true,
          properties = {
            ["solid"] = false,
            ["text1"] = "* It's a sink.[wait:5] You don't need to wash your hands."
          }
        },
        {
          id = 125,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 167.5,
          y = 114.084,
          width = 79.5,
          height = 126.833,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "houseText.fridge",
            ["solid"] = false
          }
        },
        {
          id = 132,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 152.125,
          y = 512.125,
          width = 95.5,
          height = 36.5,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "houseText.workroom",
            ["solid"] = true
          }
        }
      }
    }
  }
}
