return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 12,
  nextobjectid = 82,
  properties = {
    ["border"] = "leaves",
    ["light"] = true,
    ["music"] = "school"
  },
  tilesets = {
    {
      name = "hometownobjects",
      firstgid = 1,
      filename = "../../../../tilesets/hometownobjects.tsx",
      exportfilename = "../../../../tilesets/hometownobjects.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/maps/hometown/school/kris_class.png",
      id = 2,
      name = "room",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 76,
          y = 436,
          width = 494,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 570,
          y = 104,
          width = 40,
          height = 376,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 36,
          y = 104,
          width = 40,
          height = 376,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 76,
          y = 104,
          width = 398,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 536,
          y = 104,
          width = 34,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 278,
          y = 246,
          width = 74,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 138,
          y = 372,
          width = 74,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 278,
          y = 372,
          width = 74,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 278,
          y = 308,
          width = 74,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 414,
          y = 246,
          width = 74,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 414,
          y = 308,
          width = 74,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 414,
          y = 372,
          width = 74,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 178,
          width = 188,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 138,
          y = 246,
          width = 74,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 138,
          y = 308,
          width = 74,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/maps/hometown/school/door_open.png",
      id = 11,
      name = "dooropen",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects_deco",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 39,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 469.136,
          y = 141.852,
          width = 77.7045,
          height = 18.3523,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "nightCutscenes.school",
            ["once"] = false
          }
        },
        {
          id = 43,
          name = "npc",
          type = "",
          shape = "point",
          x = 129,
          y = 166,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "alphys_lw"
          }
        },
        {
          id = 56,
          name = "npc",
          type = "",
          shape = "point",
          x = 502.99,
          y = 142.776,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "susie_lw",
            ["cond"] = "not Game:hasPartyMember(\"susie\")"
          }
        },
        {
          id = 64,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 141.667,
          y = 306.333,
          width = 66.6667,
          height = 52.3333,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "nightCutscenes.catti",
            ["solid"] = true
          }
        },
        {
          id = 71,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 429.917,
          y = 321.966,
          width = 38.1667,
          height = 36.6969,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "nightCutscenes.mkid",
            ["solid"] = true
          }
        },
        {
          id = 74,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 428.135,
          y = 385.97,
          width = 53.8854,
          height = 46.1969,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "nightCutscenes.snowy",
            ["solid"] = true
          }
        },
        {
          id = 75,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 425.917,
          y = 239.833,
          width = 38.0834,
          height = 52.3333,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "nightCutscenes.tem",
            ["solid"] = true
          }
        },
        {
          id = 76,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 151.583,
          y = 385.985,
          width = 56.4698,
          height = 46.1818,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "nightCutscenes.jockington",
            ["solid"] = true
          }
        },
        {
          id = 78,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 547.677,
          y = 24.1029,
          width = 75.6459,
          height = 51.0833,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "nightCutscenes.schooldoor",
            ["plotmax"] = "*nf_school_interact2Alph",
            ["solid"] = true
          }
        },
        {
          id = 79,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 547.685,
          y = 24.0817,
          width = 75.6459,
          height = 51.0833,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "nightCutscenes.schooldoor2",
            ["plotmax"] = "*nf_school_interact5Alph",
            ["plotmin"] = "nf_school_interact2Alph",
            ["solid"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 412,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 23,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 348,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 23,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 286,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 23,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276,
          y = 286,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 23,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276,
          y = 412,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 23,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 412,
          y = 412,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 23,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 412,
          y = 348,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 23,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 412,
          y = 286,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 23,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 214,
          width = 188,
          height = 88,
          rotation = 0,
          gid = 26,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 426,
          y = 104,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (You checked the time...)",
            ["text2"] = "* (It's an enigma.)"
          }
        },
        {
          id = 29,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 76,
          y = 104,
          width = 82,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (Looks like motivational quotes from various literature.)",
            ["text2"] = "* \"Try your best,[wait:5] Astral Wolf!\"\n[wait:5]* \"Even in your darkest hour...!\"",
            ["text3"] = "* (... that one seems to be from a video game.)"
          }
        },
        {
          id = 30,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 330,
          y = 170,
          width = 42,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (The computer wallpaper is updated.)",
            ["text2"] = "* (... it's from the newely released season of Mew Mew Kissy Cutie.)",
            ["text3"] = "* (You decide to keep a safe distance.)"
          }
        },
        {
          id = 31,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 206,
          y = 146,
          width = 40,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a bunch of roses.)"
          }
        },
        {
          id = 32,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 473.334,
          y = 103.667,
          width = 67.3333,
          height = 41.6667,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_delay"] = 1,
            ["exit_sound"] = "doorclose",
            ["facing"] = "down",
            ["map"] = "hometown/school/school_lobby",
            ["marker"] = "entrykris",
            ["script"] = "transition.transition",
            ["solid"] = true,
            ["sound"] = "dooropen"
          }
        },
        {
          id = 41,
          name = "npc",
          type = "",
          shape = "point",
          x = 320,
          y = 304.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "berdly_lw",
            ["cutscene"] = "nightCutscenes.berdly"
          }
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276.909,
          y = 348.455,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 23,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/maps/hometown/school/classmates.png",
      id = 7,
      name = "classmates",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 33,
          name = "spawn",
          type = "",
          shape = "point",
          x = 504.417,
          y = 167.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "kris1",
          type = "",
          shape = "point",
          x = 503,
          y = 130.833,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "kris2",
          type = "",
          shape = "point",
          x = 503.833,
          y = 183.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "kris3",
          type = "",
          shape = "point",
          x = 504,
          y = 225.75,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "kris4",
          type = "",
          shape = "point",
          x = 104,
          y = 225.75,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "kris5",
          type = "",
          shape = "point",
          x = 104,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "kris6",
          type = "",
          shape = "point",
          x = 175.667,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "alphys1",
          type = "",
          shape = "point",
          x = 297,
          y = 165.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "susie1",
          type = "",
          shape = "point",
          x = 502.667,
          y = 167.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "susie2",
          type = "",
          shape = "point",
          x = 343.75,
          y = 165.75,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "susie3",
          type = "",
          shape = "point",
          x = 503.011,
          y = 135.659,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "alphys2",
          type = "",
          shape = "point",
          x = 446.375,
          y = 165.75,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "krisstand",
          type = "",
          shape = "point",
          x = 544.534,
          y = 183.886,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "alphys3",
          type = "",
          shape = "point",
          x = 447.333,
          y = 206,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "alphys4",
          type = "",
          shape = "point",
          x = 545.333,
          y = 206.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
