return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 23,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 14,
  nextobjectid = 44,
  properties = {
    ["border"] = "ground_zero",
    ["depths"] = true,
    ["light"] = false,
    ["music"] = "pirates"
  },
  tilesets = {
    {
      name = "hometownobjects",
      firstgid = 1,
      filename = "../../../../tilesets/hometownobjects.tsx",
      exportfilename = "../../../../tilesets/hometownobjects.lua"
    },
    {
      name = "depthstiles",
      firstgid = 68,
      filename = "../../../../../../../../scripts/world/tilesets/depthstiles.tsx",
      exportfilename = "../../../../../../../../scripts/world/tilesets/depthstiles.lua"
    },
    {
      name = "gateway",
      firstgid = 2584,
      filename = "../../../../../../../../scripts/world/tilesets/gateway.tsx",
      exportfilename = "../../../../../../../../scripts/world/tilesets/gateway.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/maps/hometown/interior/sans_store.png",
      id = 2,
      name = "room",
      class = "",
      visible = true,
      opacity = 0,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 12,
      id = 13,
      name = "Tile Layer 7",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJyT42JgkBvFODEywCWOTZ4Uc4nVT211tAgjSsIEm7nUUDOK6YcB85onEQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 12,
      id = 6,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -21,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFww3cBeJ7VMAPsJityMjAoATEyhTSKoyEzSbXfGLMJofGZXYqUCydCjgDi9lDDQAAejYgGg=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 12,
      id = 11,
      name = "Tile Layer 5",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -19,
      offsety = 8,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBjaYC4ndvGjLAwMx4D4OAv1zeZkZWDgAmJuVuqbPQqGP1BiZGBQZoTQ1AYwc5VpYDYx7gYAkl4FvQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 12,
      id = 10,
      name = "Tile Layer 4",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -23,
      offsety = 8,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBj6YC4ncZiQGcPJ7FEwCgYCAABZtRVn"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 12,
      id = 9,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -6,
      offsety = 8,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgZYC4nfjwSzR4Fo4DaAACXCg+R"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 12,
      id = 7,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -6,
      offsety = 7,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzLERgCAABMFP6c1MkLbMRGmLTNFWvCI+g5vZ9KQxWoK0IiJhQw6e987nQMGJC9X0bnxuPOh48Znes5m7H9BaC0o="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 12,
      id = 12,
      name = "Tile Layer 6",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 6,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgewIaDgcEWiO04qG92A9DMRiBuopLZbSwMDO1A3AHEnSwQsR4g3QvEfSyUmX0KqP80EJ8B4rNQsy4A6YtAfIlCs0fBKCAEANkYDAk="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 393.75,
          width = 40,
          height = 86.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 20.25,
          y = 394,
          width = 500,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 20.6667,
          y = 40,
          width = 40,
          height = 360,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 20.0833,
          y = 39.6667,
          width = 820,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 393.5,
          width = 40,
          height = 86.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 393.5,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 40,
          width = 40,
          height = 360,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 60,
          y = 168,
          width = 162,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 221.75,
          y = 168,
          width = 578,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 89,
          y = 149.667,
          width = 105,
          height = 78,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 244.167,
          y = 152.333,
          width = 106.333,
          height = 78,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 24,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 475.25,
          y = 197.25,
          width = 236.75,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* It's an empty help desk.[wait:5] It seems the cruise might be leaving soon."
          }
        },
        {
          id = 25,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 200,
          width = 113.5,
          height = 36.75,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (It's an empty seat.)"
          }
        },
        {
          id = 29,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 480,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["depths"] = true,
            ["facing"] = "down",
            ["map"] = "depths/crosswalk",
            ["marker"] = "sans"
          }
        },
        {
          id = 32,
          name = "npc",
          type = "",
          shape = "point",
          x = 257.045,
          y = -413.88,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "sans",
            ["cutscene"] = "depthsCutscenes.sans"
          }
        },
        {
          id = 34,
          name = "npc",
          type = "",
          shape = "point",
          x = 646.292,
          y = 224.167,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "pirates/kris",
            ["plotmax"] = "*depths_pirates"
          }
        },
        {
          id = 36,
          name = "npc",
          type = "",
          shape = "point",
          x = 606.273,
          y = 224.091,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "pirates/ralsei",
            ["plotmax"] = "*depths_pirates"
          }
        },
        {
          id = 37,
          name = "npc",
          type = "",
          shape = "point",
          x = 568,
          y = 224.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "pirates/susie",
            ["plotmax"] = "*depths_pirates"
          }
        },
        {
          id = 38,
          name = "npc",
          type = "",
          shape = "point",
          x = 527.667,
          y = 224.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "pirates/noelle",
            ["plotmax"] = "*depths_pirates"
          }
        },
        {
          id = 39,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 560.25,
          y = 418.75,
          width = 79.5,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "depthsCutscenes.meetPirates",
            ["once"] = false,
            ["plotmax"] = "*depths_pirates"
          }
        },
        {
          id = 43,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 81.25,
          y = 199.875,
          width = 113.5,
          height = 36.75,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (It's an empty seat.)"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 30,
          name = "spawn",
          type = "",
          shape = "point",
          x = 600,
          y = 440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "piratesOutside",
          type = "",
          shape = "point",
          x = 886,
          y = -104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
