return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 13,
  nextobjectid = 39,
  properties = {
    ["name"] = "Test Map - Room 1"
  },
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "../../../../assets/sprites/backgrounds/special/background.png",
      id = 6,
      name = "Image Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 0.5,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "paths",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 37,
          name = "up",
          type = "",
          shape = "polyline",
          x = 226,
          y = 414,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 39.8285, y = -0.491386 },
            { x = 60, y = -2 },
            { x = 76.4449, y = -3.86484 },
            { x = 88.3658, y = -6.47133 },
            { x = 98, y = -10 },
            { x = 112.996, y = -15.8724 },
            { x = 127.054, y = -24.7352 },
            { x = 135.202, y = -31.0413 },
            { x = 142, y = -40 },
            { x = 149.867, y = -49.4979 },
            { x = 156.754, y = -61.1241 },
            { x = 164, y = -78 },
            { x = 168.563, y = -90.3125 },
            { x = 171.849, y = -101.388 },
            { x = 174.029, y = -111.714 },
            { x = 177.266, y = -130.604 },
            { x = 180, y = -158 },
            { x = 180, y = -252 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 20,
          name = "fountainspawn",
          type = "",
          shape = "point",
          x = 406,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "spawn",
          type = "",
          shape = "point",
          x = -82,
          y = 410,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
